-- DSQL-compatible schema example
--
-- Works on: Aurora DSQL, PostgreSQL, Aurora Serverless v2, RDS PostgreSQL
-- This syntax is the safest choice when you don't know the target database.
--
-- Key differences from standard PostgreSQL:
--   - BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1) instead of SERIAL
--   - Identity columns must be BIGINT (not INTEGER)
--   - CACHE clause is required (use 1 for sequential, 65536 for high throughput)
--   - Execute each statement individually (no semicolon-batched queries)

CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT NOT NULL UNIQUE,
    display_name TEXT,
    avatar_url TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1) PRIMARY KEY,
    user_id UUID REFERENCES users(id),
    name TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'archived', 'draft')),
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1) PRIMARY KEY,
    project_id BIGINT REFERENCES projects(id),
    user_id UUID REFERENCES users(id),
    title TEXT NOT NULL,
    body TEXT,
    priority INTEGER DEFAULT 0 CHECK (priority BETWEEN 0 AND 3),
    done BOOLEAN DEFAULT false,
    due_date DATE,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1) PRIMARY KEY,
    task_id BIGINT REFERENCES tasks(id),
    user_id UUID REFERENCES users(id),
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Table without user_id: accessible to all authenticated users,
-- or controlled by custom Cedar policies.
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1) PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);
