-- 00-reset.sql — generated by conformance/fixtures/transform.mjs
-- DROP SCHEMA ... CASCADE is supported on DSQL; DROP TYPE is not.
-- public is missing on purpose: "must be owner of schema public". load.mjs
-- drops the objects inside it instead.
DROP SCHEMA IF EXISTS "test" CASCADE;
DROP SCHEMA IF EXISTS "private" CASCADE;
DROP SCHEMA IF EXISTS "postgrest" CASCADE;
DROP SCHEMA IF EXISTS "jwt" CASCADE;
DROP SCHEMA IF EXISTS "تست" CASCADE;
DROP SCHEMA IF EXISTS "extensions" CASCADE;
DROP SCHEMA IF EXISTS "v1" CASCADE;
DROP SCHEMA IF EXISTS "v2" CASCADE;
DROP SCHEMA IF EXISTS "SPECIAL ""@/\#~_-" CASCADE;
DROP SCHEMA IF EXISTS "EXTRA ""@/\#~_-" CASCADE;
