-- 03-schema.sql — generated from schema.sql by conformance/fixtures/transform.mjs
-- Do not edit: re-run the transformer.

CREATE SCHEMA postgrest;

CREATE SCHEMA private;

CREATE SCHEMA تست;

CREATE SCHEMA v1;

CREATE SCHEMA v2;

CREATE SCHEMA "SPECIAL ""@/\#~_-";

CREATE SCHEMA "EXTRA ""@/\#~_-";

COMMENT ON SCHEMA v1 IS 'v1 schema';

COMMENT ON SCHEMA v2 IS 'v2 schema';

SET search_path = public, pg_catalog;

SET search_path = "public", pg_catalog;

SET search_path = postgrest, pg_catalog;

SET search_path = "public", pg_catalog;

create domain "text/plain" as text;

create domain "text/html" as text;

create domain "application/octet-stream" as bytea;

create domain "image/png" as bytea;

create domain "application/vnd.twkb" as bytea;

create domain "application/openapi+json" as json;

create domain "application/geo+json" as jsonb;

create domain "application/vnd.geo2+json" as jsonb;

create domain "application/json" as json;

create domain "application/vnd.pgrst.object" as json;

create domain "text/tab-separated-values" as text;

create domain "text/csv" as text;

create domain "*/*" as bytea;

CREATE TABLE items (
    id bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1) primary key
);

CREATE TABLE items2 (
    id bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1) primary key
);

CREATE TABLE items3 (
    id bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1) primary key
);

CREATE FUNCTION always_true("public".items) RETURNS boolean
    LANGUAGE sql IMMUTABLE
    AS $$ SELECT true $$;

CREATE FUNCTION computed_overload("public".items) RETURNS boolean
    LANGUAGE sql IMMUTABLE
    AS $$ SELECT true $$;

CREATE FUNCTION computed_overload("public".items2) RETURNS boolean
    LANGUAGE sql IMMUTABLE
    AS $$ SELECT true $$;

CREATE FUNCTION is_first("public".items) RETURNS boolean
    LANGUAGE sql IMMUTABLE
    AS $$ SELECT $1.id = 1 $$;

CREATE FUNCTION anti_id("public".items) RETURNS bigint
    LANGUAGE sql IMMUTABLE
    AS $_$ SELECT $1.id * -1 $_$;

SET search_path = public, pg_catalog;

CREATE FUNCTION always_false("public".items) RETURNS boolean
    LANGUAGE sql IMMUTABLE
    AS $$ SELECT false $$;

CREATE TABLE public_consumers (
    id bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1) not null unique,
    name text not null check (name <> ''),
    primary key (id)
);

CREATE TABLE public_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1) not null unique,
    consumer integer not null,
    number integer not null,
    primary key (id)
);

SET search_path = تست, pg_catalog;

CREATE TABLE موارد (
    هویت bigint NOT NULL
);

SET search_path = "public", pg_catalog;

create view orders_view as
  select * from public.public_orders;

create view consumers_view as
  select * from public.public_consumers;

create view consumers_view_view as
  select * from consumers_view;

create view public.consumers_extra as
  select * from consumers_view;

create view consumers_extra_view as
  select * from public.consumers_extra;

--
-- Name: getitemrange(bigint, bigint); Type: FUNCTION; Schema: test; Owner: -
--

CREATE FUNCTION getitemrange(min bigint, max bigint) RETURNS SETOF items
    LANGUAGE sql
    STABLE
    AS $_$
    SELECT * FROM "public".items WHERE id > $1 AND id <= $2;
$_$;

--
-- Name: version(); Type: FUNCTION; Schema: test; Owner: -
--

CREATE FUNCTION noparamsproc() RETURNS text
	LANGUAGE sql
        IMMUTABLE
	AS $$
		SELECT a FROM (VALUES ('Return value of no parameters procedure.')) s(a);
	$$;

CREATE FUNCTION json_argument(arg json) RETURNS text
LANGUAGE sql
IMMUTABLE
AS $_$
  SELECT json_typeof(arg);
$_$;

CREATE FUNCTION get_current_user() RETURNS text
  LANGUAGE sql
  STABLE
  AS $$
SELECT current_user::text;
$$;

--
-- Name: reveal_big_jwt(); Type: FUNCTION; Schema: test; Owner: -
--

CREATE FUNCTION reveal_big_jwt() RETURNS TABLE (
      iss text, sub text, exp bigint,
      nbf bigint, iat bigint, jti text, "http://postgrest.com/foo" boolean
    )
AS $$
  SELECT current_setting('request.jwt.claims')::json->>'iss' as iss,
         current_setting('request.jwt.claims')::json->>'sub' as sub,
         (current_setting('request.jwt.claims')::json->>'exp')::bigint as exp,
         (current_setting('request.jwt.claims')::json->>'nbf')::bigint as nbf,
         (current_setting('request.jwt.claims')::json->>'iat')::bigint as iat,
         current_setting('request.jwt.claims')::json->>'jti' as jti,
         (current_setting('request.jwt.claims')::json->>'http://postgrest.com/foo')::boolean as "http://postgrest.com/foo";
$$ LANGUAGE sql SECURITY DEFINER STABLE;

--
-- Name: sayhello(text); Type: FUNCTION; Schema: test; Owner: -
--

CREATE FUNCTION sayhello(name text) RETURNS text
    LANGUAGE sql
    IMMUTABLE
    AS $_$
    SELECT 'Hello, ' || $1;
$_$;

CREATE SEQUENCE callcounter_count START 1 CACHE 1;

CREATE FUNCTION callcounter() RETURNS bigint
    LANGUAGE sql
    AS $_$
    SELECT nextval('"public".callcounter_count');
$_$;

--
-- Name: singlejsonparam(json); Type: FUNCTION; Schema: test; Owner: -
--

CREATE FUNCTION singlejsonparam(single_param json) RETURNS json
    LANGUAGE sql
    IMMUTABLE
    AS $_$
    SELECT single_param;
$_$;

--
-- Name: test_empty_rowset(); Type: FUNCTION; Schema: test; Owner: -
--

CREATE FUNCTION test_empty_rowset() RETURNS SETOF integer
    LANGUAGE sql
    IMMUTABLE
    AS $$
    SELECT null::int FROM (SELECT 1) a WHERE false;
$$;

SET search_path = postgrest, pg_catalog;

CREATE TABLE auth (
    id character varying NOT NULL,
    rolname name DEFAULT 'postgrest_test_author'::name NOT NULL,
    pass character(60) NOT NULL,
    PRIMARY KEY (id)
);

SET search_path = "public", pg_catalog;

CREATE TABLE authors_only (
    owner character varying NOT NULL,
    secret character varying NOT NULL,
    PRIMARY KEY (secret)
);

CREATE TABLE auto_incrementing_pk (
    id integer NOT NULL,
    nullable_string character varying,
    non_nullable_string character varying NOT NULL,
    inserted_at timestamp with time zone DEFAULT now(),
    PRIMARY KEY (id)
);

CREATE SEQUENCE auto_incrementing_pk_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: auto_incrementing_pk_id_seq; Type: SEQUENCE OWNED BY; Schema: test; Owner: -
--

ALTER SEQUENCE auto_incrementing_pk_id_seq OWNED BY auto_incrementing_pk.id;

CREATE TABLE clients (
    id integer primary key,
    name text NOT NULL
);

CREATE TABLE complex_items (
    id bigint NOT NULL,
    name text,
    settings json,
    "field-with_sep" integer default 1 not null,
    PRIMARY KEY (id)
);

CREATE TABLE compound_pk (
    PRIMARY KEY (k1, k2),
    k1 integer NOT NULL,
    k2 text NOT NULL,
    extra integer
);

CREATE VIEW compound_pk_view AS
SELECT * FROM compound_pk;

CREATE TABLE empty_table (
    k character varying NOT NULL,
    extra character varying NOT NULL
);

--
-- Name: has_count_column; Type: VIEW; Schema: test; Owner: -
--

CREATE VIEW has_count_column AS
 SELECT 1 AS count;

CREATE TABLE has_fk (
    id bigint NOT NULL,
    auto_inc_fk integer,
    simple_fk character varying(255),
    PRIMARY KEY (id)
);

CREATE SEQUENCE has_fk_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: has_fk_id_seq; Type: SEQUENCE OWNED BY; Schema: test; Owner: -
--

ALTER SEQUENCE has_fk_id_seq OWNED BY has_fk.id;

--
-- Name: insertable_view_with_join; Type: VIEW; Schema: test; Owner: -
--

CREATE VIEW insertable_view_with_join AS
 SELECT has_fk.id,
    has_fk.auto_inc_fk,
    has_fk.simple_fk,
    auto_incrementing_pk.nullable_string,
    auto_incrementing_pk.non_nullable_string,
    auto_incrementing_pk.inserted_at
   FROM (has_fk
     JOIN auto_incrementing_pk USING (id));

CREATE TABLE json_table (
    data json
);

CREATE TABLE menagerie (
    "integer" integer NOT NULL,
    double double precision NOT NULL,
    "varchar" character varying NOT NULL,
    "boolean" boolean NOT NULL,
    date date NOT NULL,
    PRIMARY KEY ("integer")
);

CREATE TABLE no_pk (
    a character varying,
    b character varying
);

CREATE TABLE only_pk (
    id integer primary key
);

CREATE TABLE nullable_integer (
    a integer
);

CREATE TABLE insertonly (
    v text NOT NULL
);

CREATE TABLE projects (
    id integer primary key,
    name text NOT NULL,
    client_id integer
);

--
-- Name: projects_view; Type: VIEW; Schema: test; Owner: -
--

CREATE VIEW projects_view AS
 SELECT projects.id,
    projects.name,
    projects.client_id
   FROM projects;

CREATE VIEW projects_view_alt AS
 SELECT projects.id as t_id,
    projects.name,
    projects.client_id as t_client_id
   FROM projects;

CREATE TABLE sponsors (
    id integer primary key,
    name varchar(20) not null
);

CREATE TABLE competitors (
    id integer primary key,
    sponsor_id integer,
    full_name varchar(40) not null
);

CREATE VIEW test_null_pk_competitors_sponsors  AS
SELECT c.id, s.id as sponsor_id
FROM competitors c
    LEFT JOIN sponsors s on c.sponsor_id = s.id;

CREATE TABLE simple_pk (
    PRIMARY KEY (k),
    k character varying NOT NULL,
    extra character varying NOT NULL
);

CREATE TABLE simple_pk2 (
    PRIMARY KEY (k),
    k character varying NOT NULL,
    extra character varying NOT NULL
);

CREATE TABLE users (
    id integer primary key,
    name text NOT NULL
);

CREATE TABLE users_projects (
    user_id integer NOT NULL,
    project_id integer NOT NULL,
    PRIMARY KEY (project_id, user_id)
);

CREATE TABLE tasks (
    id integer primary key,
    name text NOT NULL,
    project_id integer
);

CREATE OR REPLACE VIEW filtered_tasks AS
SELECT id AS "myId", name, project_id AS "projectID"
FROM tasks
WHERE project_id IN (
	SELECT id FROM projects WHERE id = 1
) AND
project_id IN (
	SELECT project_id FROM users_projects WHERE user_id = 1
);

CREATE TABLE users_tasks (
    user_id integer NOT NULL,
    task_id integer NOT NULL,
    primary key (task_id, user_id)
);

CREATE TABLE comments (
    id integer primary key,
    commenter_id integer NOT NULL,
    user_id integer NOT NULL,
    task_id integer NOT NULL,
    content text NOT NULL
);

CREATE TABLE files (
    project_id integer NOT NULL,
    filename text NOT NULL,
    content text NOT NULL,
    PRIMARY KEY (project_id, filename)
);

CREATE TABLE touched_files (
    user_id integer NOT NULL,
    task_id integer NOT NULL,
    project_id integer NOT NULL,
    filename text NOT NULL,
    primary key(user_id, task_id, project_id, filename)
);

CREATE TABLE private.articles (
    id integer primary key,
    body text,
    owner name not null
);

CREATE TABLE private.article_stars (
    article_id integer not null,
    user_id integer not null,
    created_at timestamp without time zone default now() not null,
    primary key (article_id, user_id)
);

CREATE VIEW limited_article_stars AS
  SELECT article_id, user_id, created_at FROM private.article_stars;

CREATE VIEW "articleStars" AS
 SELECT article_stars.article_id AS "articleId",
    article_stars.user_id AS "userId",
    article_stars.created_at AS "createdAt"
   FROM private.article_stars;

CREATE VIEW articles AS
 SELECT articles.id,
    articles.body,
    articles.owner
   FROM private.articles;

CREATE TABLE "Escap3e;" (
    "so6meIdColumn" integer primary key
);

CREATE TABLE "ghostBusters" (
    "escapeId" integer not null
);

CREATE TABLE "withUnique" (
    uni text UNIQUE,
    extra text
);

CREATE TABLE clashing_column (
    t text
);

--
-- Name: id; Type: DEFAULT; Schema: test; Owner: -
--

ALTER TABLE ONLY auto_incrementing_pk ALTER COLUMN id SET DEFAULT nextval('auto_incrementing_pk_id_seq'::regclass);

--
-- Name: id; Type: DEFAULT; Schema: test; Owner: -
--

ALTER TABLE ONLY has_fk ALTER COLUMN id SET DEFAULT nextval('has_fk_id_seq'::regclass);

SET search_path = postgrest, pg_catalog;

SET search_path = "public", pg_catalog;

SET search_path = postgrest, pg_catalog;

SET search_path = private, pg_catalog;

SET search_path = "public", pg_catalog;

SET search_path = "public", pg_catalog;

CREATE TABLE addresses (
    id int not null unique,
    address text not null
);

CREATE TABLE orders (
    id int not null unique,
    name text not null,
    billing_address_id int,
    shipping_address_id int
);

CREATE FUNCTION getproject(id int) RETURNS SETOF projects
    LANGUAGE sql
    AS $_$
    SELECT * FROM "public".projects WHERE id = $1;
$_$;

CREATE FUNCTION get_projects_below(id int) RETURNS SETOF projects
    LANGUAGE sql
    AS $_$
    SELECT * FROM "public".projects WHERE id < $1;
$_$;

CREATE FUNCTION get_projects_above(id int) RETURNS SETOF projects
    LANGUAGE sql
    AS $_$
    SELECT * FROM "public".projects WHERE id > $1;
$_$ ROWS 1;

CREATE FUNCTION getallprojects() RETURNS SETOF projects
    LANGUAGE sql
    AS $_$
    SELECT * FROM "public".projects;
$_$ ROWS 2019;

CREATE FUNCTION setprojects(id_l int, id_h int, name text) RETURNS SETOF projects
    LANGUAGE sql
    AS $_$
    update "public".projects set name = $3 WHERE id >= $1 AND id <= $2 returning *;
$_$;

CREATE TABLE images (
    name text not null,
    img bytea not null
);

create view images_base64 as (
  -- encoding in base64 puts a '\n' after every 76 character due to legacy reasons, this is isn't necessary here so it's removed
  select name, replace(encode(img, 'base64'), E'\n', '') as img from images
);

create domain one_nine as integer check (value >= 1 and value <= 9);

create function "public".ret_array() returns integer[] as $$
  select '{1,2,3}'::integer[];
$$ language sql;

create function "public".ret_domain(val integer) returns "public".one_nine as $$
  select val::"public".one_nine;
$$ language sql;

create function "public".ret_setof_integers() returns setof integer as $$
  values (1), (2), (3);
$$ language sql;

-- this function does not have named arguments and should be ignored
-- if it's not ignored, it will break the test for the function before
create function "public".ret_setof_integers(int, int) returns integer AS $$
  values (1);
$$ language sql;

create function "public".ret_void() returns void as '' language sql;

create or replace function "public".ret_null() returns int as $$
  select null::int;
$$ language sql;

create function "public".ret_image() returns "image/png" as $$
  select i.img::"image/png" from "public".images i where i.name = 'A.png';
$$ language sql;

create function "public".single_article(id integer) returns "public".articles as $$
  select a.* from "public".articles a where a.id = $1;
$$ language sql;

create function "public".get_guc_value(name text) returns text as $$
  select nullif(current_setting(name), '')::text;
$$ language sql;

-- Get the JSON type GUC values
create function "public".get_guc_value(prefix text, name text) returns text as $$
select nullif(current_setting(prefix)::json->>name, '')::text;
$$ language sql;

CREATE TABLE w_or_wo_comma_names (
    name text
);

CREATE TABLE items_with_different_col_types (
    int_data integer,
    text_data text,
    bool_data bool,
    bin_data bytea,
    char_data character varying,
    date_data date,
    real_data real,
    time_data time
);

CREATE TABLE entities (
    id integer primary key,
    name text
);

CREATE TABLE child_entities (
    id integer primary key,
    name text,
    parent_id integer
);

create view child_entities_view as table child_entities;

CREATE TABLE grandchild_entities (
    id integer primary key,
    name text,
    parent_id integer,
    or_starting_col text,
    and_starting_col text,
    jsonb_col jsonb
);

CREATE TABLE ranges (
    id integer primary key
);

-- OpenAPI description tests

comment on table child_entities is 'child_entities comment';

comment on column child_entities.id is 'child_entities id comment';

comment on column child_entities.name is 'child_entities name comment. Can be longer than sixty-three characters long';

comment on view child_entities_view is 'child_entities_view comment';

comment on column child_entities_view.id is 'child_entities_view id comment';

comment on column child_entities_view.name is 'child_entities_view name comment. Can be longer than sixty-three characters long';

comment on table grandchild_entities is
$$grandchild_entities summary

grandchild_entities description
that spans
multiple lines$$;

-- Used for testing that having the same return column name as the proc name
-- doesn't conflict with the required output, details in #901
create function "public".test() returns table(test text, value int) as $$
  values ('hello', 1);
$$ language sql;

create function "public".privileged_hello(name text) returns text as $$
  select 'Privileged hello to ' || $1;
$$ language sql;

CREATE TABLE "public".being (
    being int primary key not null
);

CREATE TABLE "public".descendant (
    descendant int primary key not null,
    being int
);

CREATE TABLE "public".part (
    part int primary key not null
);

CREATE TABLE "public".being_part (
    being int not null,
    part int not null,
    primary key(being, part)
);

create function "public".single_out_param(num int, OUT num_plus_one int) AS $$
  select num + 1;
$$ language sql;

create function "public".single_json_out_param(a int, b text, OUT my_json json) AS $$
  select json_build_object('a', a, 'b', b);
$$ language sql;

create function "public".many_out_params(OUT my_json json, OUT num int, OUT str text) AS $$
  select '{"a": 1, "b": "two"}'::json, 3, 'four'::text;
$$ language sql;

create function "public".single_inout_param(INOUT num int) AS $$
  select num + 1;
$$ language sql;

create function "public".many_inout_params(INOUT num int, INOUT str text, INOUT b bool DEFAULT true) AS $$
  select num, str, b;
$$ language sql;

create function "public".single_column_table_return () returns table (a text) AS $$
  select 'A'::text;
$$ language sql;

create function "public".multi_column_table_return () returns table (a text, b text) AS $$
  select 'A'::text, 'B'::text;
$$ language sql;

CREATE FUNCTION "public".variadic_param(VARIADIC v TEXT[] DEFAULT '{}') RETURNS text[]
IMMUTABLE
LANGUAGE SQL AS $$
  SELECT v
$$;

CREATE FUNCTION "public".sayhello_variadic(name TEXT, VARIADIC v TEXT[]) RETURNS text
IMMUTABLE
LANGUAGE SQL AS $$
  SELECT 'Hello, ' || name
$$;

create or replace function "public".three_defaults(a int default 1, b int default 2, c int default 3) returns int as $$
select a + b + c
$$ language sql;

create or replace function "public".overloaded() returns setof int as $$
  values (1), (2), (3);
$$ language sql;

create or replace function "public".overloaded(json) returns table(x int, y text) as $$
  select * from json_to_recordset($1) as r(x int, y text);
$$ language sql;

create or replace function "public".overloaded(a int, b int) returns int as $$
  select a + b
$$ language sql;

create or replace function "public".overloaded(a text, b text, c text) returns text as $$
  select a || b || c
$$ language sql;

create or replace function "public".overloaded_default(opt_param text default 'Code w7') returns setof "public".tasks as $$
select * from "public".tasks where name like opt_param;
$$ language sql;

create or replace function "public".overloaded_default(must_param int) returns jsonb as $$
select row_to_json(r)::jsonb from (select must_param as val) as r;
$$ language sql;

create or replace function "public".overloaded_default(a int, opt_param text default 'Design IOS') returns setof "public".tasks as $$
select * from "public".tasks where name like opt_param and id > a;
$$ language sql;

create or replace function "public".overloaded_default(a int, must_param int) returns jsonb as $$
select row_to_json(r)::jsonb from (select a, must_param as val) as r;
$$ language sql;

create or replace function "public".overloaded_html_form() returns setof int as $$
values (1), (2), (3);
$$ language sql;

create or replace function "public".overloaded_html_form(single_param json) returns json as $$
select single_param;
$$ language sql;

create or replace function "public".overloaded_html_form(a int, b int) returns int as $$
select a + b
$$ language sql;

create or replace function "public".overloaded_html_form(a text, b text, c text) returns text as $$
select a || b || c
$$ language sql;

create or replace function "public".overloaded_same_args(arg integer) returns json as $$
select json_build_object(
    'type', pg_typeof(arg),
    'value', arg
  );
$$ language sql;

create or replace function "public".overloaded_same_args(arg xml) returns json as $$
select json_build_object(
    'type', pg_typeof(arg),
    'value', arg
  );
$$ language sql;

create or replace function "public".overloaded_same_args(arg text, num integer default 0) returns json as $$
select json_build_object(
    'type', pg_typeof(arg),
    'value', arg
  );
$$ language sql;

CREATE TABLE "public".leak (
    id bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1) primary key,
    blob bytea
);

CREATE TABLE "public".perf_articles (
    id integer not null,
    body text not null
);

CREATE TABLE "public".employees (
    first_name text,
    last_name text,
    company text,
    occupation text,
    primary key(first_name, last_name)
);

CREATE TABLE "public".tiobe_pls (
    name text primary key,
    rank smallint
);

CREATE TABLE "public".single_unique (
    unique_key integer unique not null,
    value text
);

CREATE TABLE "public".compound_unique (
    key1 integer not null,
    key2 integer not null,
    value text,
    unique(key1, key2)
);

CREATE TABLE "public".family_tree (
    id text not null primary key,
    name text not null,
    parent text
);

CREATE TABLE "public".managers (
    id integer primary key,
    name text
);

CREATE TABLE "public".organizations (
    id integer primary key,
    name text,
    referee integer,
    auditor integer,
    manager_id integer
);

CREATE TABLE private.authors (
    id integer primary key,
    name text
);

CREATE TABLE private.publishers (
    id integer primary key,
    name text
);

CREATE TABLE private.books (
    id integer primary key,
    title text,
    publication_year smallint,
    author_id integer,
    first_publisher_id integer
);

create view "public".authors as select id, name from private.authors;

create view "public".publishers as select id, name from private.publishers;

create view "public".books as select id, title, publication_year, author_id, first_publisher_id from private.books;

create view "public".forties_books as select id, title, publication_year, author_id from private.books where publication_year >= 1940 and publication_year < 1950;

create view "public".fifties_books as select id, title, publication_year, author_id from private.books where publication_year >= 1950 and publication_year < 1960;

create view "public".sixties_books as select id, title, publication_year, author_id from private.books where publication_year >= 1960 and publication_year < 1970;

CREATE TABLE person (
    id integer primary key,
    name character varying not null
);

CREATE TABLE message (
    id integer primary key,
    body text not null default '',
    sender bigint not null,
    recipient bigint not null
);

create view person_detail as
  select p.id, p.name, s.count as sent, r.count as received
  from person p
  join lateral (select message.sender, count(message.id) as count from message group by message.sender) s on s.sender = p.id
  join lateral (select message.recipient, count(message.id) as count from message group by message.recipient) r on r.recipient = p.id;

CREATE TABLE space (
    id integer primary key,
    name text
);

CREATE TABLE zone (
    id integer primary key,
    name text,
    zone_type_id integer,
    space_id integer
);

CREATE TABLE "UnitTest" (
    "idUnitTest" integer primary key,
    "nameUnitTest" text
);

CREATE TABLE json_arr (
    id integer primary key,
    data json
);

CREATE TABLE jsonb_test (
    id integer primary key,
    data jsonb
);

create view "public".authors_books_number as
select
  id,
  name,
  (
    select
      count(*)
    from forties_books where author_id = authors.id
  ) as num_in_forties,
  (
    select
      count(*)
    from fifties_books where author_id = authors.id
  ) as num_in_fifties,
  (
    select
      count(*)
    from sixties_books where author_id = authors.id
  ) as num_in_sixties,
  (
    select
      count(*)
    from (
      select id
      from forties_books where author_id = authors.id
      union
      select id
      from fifties_books where author_id = authors.id
      union
      select id
      from sixties_books where author_id = authors.id
    ) _
  ) as num_in_all_decades
from private.authors;

create view "public".authors_have_book_in_decade as
select
  id,
  name,
  case
    when (x.id in (select author_id from "public".forties_books))
    then true
    else false
  end as has_book_in_forties,
  case
    when (x.id in (select author_id from "public".fifties_books))
    then true
    else false
  end as has_book_in_fifties,
  case
    when (x.id in (select author_id from "public".sixties_books))
    then true
    else false
  end as has_book_in_sixties
from private.authors x;

create view "public".authors_have_book_in_decade2 as
select
  id,
  name,
  coalesce(
    (select true from "public".forties_books where author_id=x.id limit 1),
    false
  ) as has_book_in_forties,
  coalesce(
    (select true from "public".fifties_books where author_id=x.id limit 1),
    false
  ) as has_book_in_fifties,
  coalesce(
    (select true from "public".sixties_books where author_id=x.id limit 1),
    false
  ) as has_book_in_sixties
from private.authors x;

create view "public".forties_and_fifties_books as
select x.id, x.title, x.publication_year, y.name as first_publisher, x.author_id
from (
  select id, title, publication_year, author_id, first_publisher_id from private.books
  where publication_year >= 1940 and publication_year < 1960) x
join private.publishers y on y.id = x.first_publisher_id;

create view "public".odd_years_publications as
with
odd_years_books as(
  select id, title, publication_year, author_id, first_publisher_id
  from private.books
  where publication_year % 2 <> 0
)
select
  x.id, x.title, x.publication_year,
  y.name as first_publisher, x.author_id
from odd_years_books x
join private.publishers y on y.id = x.first_publisher_id;

create view "public".projects_count_grouped_by as
select
  client_id,
  count(id) as number_of_projects
from projects
group by client_id;

create view "public".authors_w_entities as
select
  id,
  name,
  (
    select json_agg(id)
    from "public".entities
    where id not in (
      select parent_id from "public".child_entities
    )
  ) as entities
from private.authors;

CREATE TABLE "public"."Foo" (
    id int primary key,
    name text
);

CREATE TABLE "public".bar (
    id int primary key,
    name text,
    "fooId" int
);

CREATE VIEW "public".foos as select id,name from "Foo";

CREATE VIEW "public".bars as select id, "fooId", name from bar;

-- Tests for updatable, insertable and deletable views
create view "public".projects_auto_updatable_view_with_pk as
select id, name, client_id from "public".projects;

create view "public".projects_auto_updatable_view_without_pk as
select name, client_id from "public".projects;

create view "public".projects_view_without_triggers as
select distinct id, name, client_id from "public".projects;

create view "public".projects_view_with_all_triggers_with_pk as
select distinct id, name, client_id from "public".projects;

create view "public".projects_view_with_all_triggers_without_pk as
select distinct name, client_id from "public".projects;

create view "public".projects_view_with_insert_trigger as
select distinct id, name, client_id from "public".projects;

create view "public".projects_view_with_update_trigger as
select distinct id, name, client_id from "public".projects;

create view "public".projects_view_with_delete_trigger as
select distinct id, name, client_id from "public".projects;

create or replace function "public"."quotedFunction"("user" text, "fullName" text, "SSN" text)
returns jsonb AS $$
  select format('{"user": "%s", "fullName": "%s", "SSN": "%s"}', "user", "fullName", "SSN")::jsonb;
$$ language sql;

CREATE TABLE private.player (
    id integer not null,
    first_name text not null,
    last_name text not null,
    birth_date date,
    primary key (last_name, id, first_name, birth_date)
);

CREATE TABLE "public".contract (
    tournament text not null,
    purchase_price int not null,
    id integer not null,
    first_name text not null,
    last_name text not null,
    birth_date date
);

create view "public".player_view as select * from private.player;

create view "public".contract_view as select * from "public".contract;

CREATE TABLE "public".isn_sample (
    name text
);

CREATE TABLE "Server Today" (
    "cHostname" text,
    "Just A Server Model" text
);

CREATE TABLE "public".pgrst_reserved_chars (
    "*id*" integer,
    ":arr->ow::cast" text,
    "(inside,parens)" text,
    "a.dotted.column" text,
    "  col  w  space  " text
);

CREATE TABLE "public".openapi_types (
    "a_character_varying" character varying,
    "a_character" character(1),
    "a_text" text,
    "a_boolean" boolean,
    "a_smallint" smallint,
    "a_integer" integer,
    "a_bigint" bigint,
    "a_numeric" numeric,
    "a_real" real,
    "a_double_precision" double precision,
    "a_json" json,
    "a_jsonb" jsonb
);

CREATE TABLE "public".openapi_defaults (
    "text" text default 'default',
    "boolean" boolean default false,
    "integer" integer default 42,
    "numeric" numeric default 42.2,
    "date" date default '1900-01-01'::date,
    "time" time default '13:00:00'::time without time zone
);

create function add_them(a integer, b integer)
returns integer as $$
  select a + b;
$$ language sql;

create or replace function welcome() returns "text/plain" as $$
select 'Welcome to PostgREST'::"text/plain";
$$ language sql;

create or replace function welcome_twice() returns setof "text/plain" as $$
select 'Welcome to PostgREST'
union all
select 'Welcome to PostgREST';
$$ language sql;

create or replace function "welcome.html"() returns "text/html" as $_$
select $$
<html>
  <head>
    <title>PostgREST</title>
  </head>
  <body>
    <h1>Welcome to PostgREST</h1>
  </body>
</html>
$$::"text/html";
$_$ language sql;

create view getallprojects_view as
select * from getallprojects();

create view get_projects_above_view as
select * from get_projects_above(1);

CREATE TABLE web_content (
    id integer,
    name text,
    p_web_id integer,
    primary key (id)
);

CREATE FUNCTION getallusers() RETURNS SETOF users AS $$
  SELECT * FROM "public".users;
$$ LANGUAGE sql STABLE;

CREATE TABLE app_users (
    id integer primary key,
    email text unique not null,
    password text not null
);

CREATE TABLE private.pages (
    link int not null unique,
    url text
);

CREATE TABLE private.referrals (
    site text,
    link int not null
);

create view "public".pages as select * from private.pages;

create view "public".referrals as select * from private.referrals;

CREATE TABLE big_projects (
    big_project_id bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1) primary key,
    name text
);

CREATE TABLE sites (
    site_id bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1) primary key,
    name text,
    main_project_id int null
);

CREATE TABLE jobs (
    job_id uuid,
    name text,
    site_id int not null,
    big_project_id int not null,
    primary key(job_id, site_id, big_project_id)
);

create view main_jobs as
select * from jobs
where site_id in (select site_id from sites where main_project_id is not null);

-- junction in a private schema, just to make sure we don't leak it on resource embedding
-- if it leaks it would show on the disambiguation error tests
create view private.priv_jobs as
  select * from jobs;

CREATE TABLE whatev_projects (
    id bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1) primary key,
    name text
);

CREATE TABLE whatev_sites (
    id bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1) primary key,
    name text
);

CREATE TABLE whatev_jobs (
    job_id uuid,
    name text,
    site_id_1 int not null,
    project_id_1 int not null,
    site_id_2 int not null,
    project_id_2 int not null,
    primary key(job_id, site_id_1, project_id_1, site_id_2, project_id_2)
);

CREATE TABLE agents (
    id int primary key,
    name text,
    department_id int
);

CREATE TABLE departments (
    id int primary key,
    name text,
    head_id int
);

CREATE TABLE schedules (
    id int primary key,
    name text,
    start_at timetz,
    end_at timetz
);

CREATE TABLE activities (
    id int,
    schedule_id int,
    car_id text,
    camera_id text,
    primary key (id, schedule_id)
);

CREATE TABLE unit_workdays (
    unit_id int,
    day date,
    fst_shift_activity_id int,
    fst_shift_schedule_id int,
    snd_shift_activity_id int,
    snd_shift_schedule_id int,
    primary key (unit_id, day)
);

create view unit_workdays_fst_shift as
select unit_id, day, fst_shift_activity_id, fst_shift_schedule_id
from unit_workdays
where fst_shift_activity_id is not null
  and fst_shift_schedule_id is not null;

CREATE TABLE private.stuff (
    id integer primary key,
    name text
);

create view "public".stuff as select * from private.stuff;

CREATE TABLE loc_test (
    id int primary key,
    c text
);

CREATE TABLE v1.parents (
    id int primary key,
    name text
);

CREATE TABLE v1.children (
    id int primary key,
    name text,
    parent_id int
);

create function v1.get_parents_below(id int)
returns setof v1.parents as $$
  select * from v1.parents where id < $1;
$$ language sql;

CREATE TABLE v2.parents (
    id int primary key,
    name text
);

CREATE TABLE v2.children (
    id int primary key,
    name text,
    parent_id int
);

CREATE TABLE v2.another_table (
    id int primary key,
    another_value text
);

create function v2.get_parents_below(id int)
returns setof v2.parents as $$
  select * from v2.parents where id < $1;
$$ language sql;

create function v2.get_plain_text()
returns "public"."text/plain" as $$
  select 'plain'::"public"."text/plain";
$$ language sql;

create domain v2."text/special" as text;

create function v2.get_special_text()
returns v2."text/special" as $$
  select 'special'::v2."text/special";
$$ language sql;

create or replace function v2.special_trans (state v2."text/special", next v2.another_table)
returns v2."text/special" as $$
  select 'special'::v2."text/special";
$$ language sql;

create or replace function v2.plain_trans (state "public"."text/plain", next v2.another_table)
returns "public"."text/plain" as $$
  select 'plain'::"public"."text/plain";
$$ language sql;

CREATE TABLE private.screens (
    id bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1) primary key,
    name text not null default 'new screen'
);

CREATE TABLE private.labels (
    id bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1) primary key,
    name text not null default 'new label'
);

CREATE TABLE private.label_screen (
    label_id int not null,
    screen_id int not null,
    constraint label_screen_pkey primary key (label_id, screen_id)
);

create view "public".labels as
select * from private.labels;

create view "public".screens as
select * from private.screens;

create view "public".label_screen as
select * from private.label_screen;

CREATE TABLE private.actors (
    id int,
    name text,
    constraint actors_id primary key (id)
);

CREATE TABLE private.films (
    id integer,
    title text,
    constraint films_id primary key (id)
);

CREATE TABLE private.personnages (
    film_id int not null,
    role_id int not null,
    character text not null,
    constraint personnages_film_id_role_id primary key (film_id, role_id)
);

create view "public".actors as
select * from private.actors;

create view "public".films as
select * from private.films;

create view "public".personnages as
select * from private.personnages;

CREATE TABLE "public".end_1 (
    id int primary key,
    name text
);

CREATE TABLE "public".end_2 (
    id int primary key,
    name text
);

CREATE TABLE private.junction (
    end_1_id int not null,
    end_2_id int not null,
    primary key (end_1_id, end_2_id)
);

CREATE TABLE "public".schauspieler (
    id int primary key,
    name text
);

CREATE TABLE "public".filme (
    id int primary key,
    titel text
);

CREATE TABLE private.rollen (
    film_id int not null,
    rolle_id int not null,
    charakter text not null,
    primary key (film_id, rolle_id)
);

CREATE TABLE "public".car_brands (
    name varchar(64) primary key
);

create or replace function "public".unnamed_json_param(json) returns json as $$
  select $1;
$$ language sql;

-- Function with a NAMED json parameter (for testing single param fallback behavior)
create or replace function "public".named_json_param(data json) returns json as $$
  select data;
$$ language sql;

create or replace function "public".unnamed_text_param(text) returns "text/plain" as $$
  select $1::"text/plain";
$$ language sql;

create or replace function "public".unnamed_bytea_param(bytea) returns "application/octet-stream" as $$
  select $1::"application/octet-stream";
$$ language sql;

create or replace function "public".unnamed_int_param(int) returns int as $$
  select $1;
$$ language sql;

create or replace function "public".overloaded_unnamed_param(json) returns json as $$
  select $1;
$$ language sql;

create or replace function "public".overloaded_unnamed_param(bytea) returns "application/octet-stream" as $$
select $1::"application/octet-stream";
$$ language sql;

create or replace function "public".overloaded_unnamed_param(text) returns "text/plain" as $$
select $1::"text/plain";
$$ language sql;

create or replace function "public".overloaded_unnamed_param() returns int as $$
select 1;
$$ language sql;

create or replace function "public".overloaded_unnamed_param(x int, y int) returns int as $$
  select x + y;
$$ language sql;

create or replace function "public".overloaded_unnamed_json_jsonb_param(json) returns json as $$
select $1;
$$ language sql;

create or replace function "public".overloaded_unnamed_json_jsonb_param(jsonb) returns jsonb as $$
select $1;
$$ language sql;

create or replace function "public".overloaded_unnamed_json_jsonb_param(x int, y int) returns int as $$
select x + y;
$$ language sql;

CREATE TABLE products (
    id int primary key,
    name text
);

CREATE TABLE suppliers (
    id int primary key,
    name text
);

CREATE TABLE products_suppliers (
    product_id int,
    supplier_id int,
    primary key (product_id, supplier_id)
);

CREATE TABLE trade_unions (
    id int primary key,
    name text
);

CREATE TABLE suppliers_trade_unions (
    supplier_id int,
    trade_union_id int,
    primary key (supplier_id, trade_union_id)
);

CREATE TABLE client (
    id int primary key,
    name text
);

CREATE TABLE contact (
    id int primary key,
    name text,
    clientid int
);

CREATE TABLE clientinfo (
    id bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1) primary key,
    clientid int,
    other text
);

CREATE TABLE chores (
    id int primary key,
    name text,
    done bool
);

CREATE TABLE deferrable_unique_constraint (
    col INT UNIQUE
);

CREATE TABLE "public".fav_numbers (
    person text
);

CREATE TABLE "public".arrays (
    id int primary key
);

CREATE FUNCTION public.dummy(int) RETURNS int
LANGUAGE SQL AS $$ SELECT 1 $$;

CREATE TABLE plate (
    plate_id int primary key
);

CREATE TABLE well (
    well_id int primary key,
    plate_id int not null,
    parent_well_id int
);

CREATE TABLE plate_plan_step (
    plate_plan_step_id int primary key,
    from_well_id int,
    to_well_id int,
    to_plate_id int
);

CREATE TABLE oid_test (
    id int,
    oid_col oid
);

CREATE TABLE private.internal_job (
    id integer NOT NULL,
    parent_id integer,
    CONSTRAINT internal_job_pkey PRIMARY KEY (id)
);

CREATE VIEW "public".job AS
SELECT j.id, j.parent_id
FROM private.internal_job j;

CREATE TABLE series (
    id bigint PRIMARY KEY,
    title text NOT NULL
);

CREATE TABLE adaptation_notifications (
    id bigint PRIMARY KEY,
    series bigint,
    status text
);

CREATE VIEW series_popularity AS
SELECT id, random() AS popularity_score
FROM series;

CREATE TABLE "public".test (
    id BIGINT NOT NULL PRIMARY KEY,
    parent_id BIGINT
);

CREATE OR REPLACE VIEW "public".view_test AS
  SELECT id FROM "public".test;

CREATE TABLE shops (
    id int primary key,
    address text
);

CREATE TABLE shop_bles (
    id int primary key,
    name text,
    shop_id int
);

create function get_shop(id int) returns shops as $$
  select * from shops where id = $1;
$$ language sql;

CREATE TABLE "SPECIAL ""@/\#~_-".languages (
    id INT PRIMARY KEY,
    name TEXT
);

CREATE TABLE "SPECIAL ""@/\#~_-".names (
    id INT PRIMARY KEY,
    name TEXT,
    language_id INT
);

CREATE FUNCTION "SPECIAL ""@/\#~_-".computed_languages("SPECIAL ""@/\#~_-".names) RETURNS SETOF "SPECIAL ""@/\#~_-".languages ROWS 1 AS $$
  SELECT * FROM "SPECIAL ""@/\#~_-".languages where id = $1.language_id;
$$ LANGUAGE sql;

CREATE FUNCTION "EXTRA ""@/\#~_-".get_val_special(val text) RETURNS text AS $$
  SELECT val;
$$ LANGUAGE sql;

CREATE FUNCTION "public".special_extended_schema(val text) RETURNS text AS $$
  SELECT get_val_special(val);
$$ LANGUAGE sql;

CREATE TABLE do$llar$s (
    a$num$ numeric
);

CREATE TABLE "public".safe_update_items (
    id INT PRIMARY KEY,
    name TEXT,
    observation TEXT
);

CREATE TABLE "public".safe_delete_items (
    id INT PRIMARY KEY,
    name TEXT,
    observation TEXT
);

CREATE TABLE "public".unsafe_update_items (
    id INT PRIMARY KEY,
    name TEXT,
    observation TEXT
);

CREATE TABLE "public".unsafe_delete_items (
    id INT PRIMARY KEY,
    name TEXT,
    observation TEXT
);

DROP DOMAIN IF EXISTS public.titlecasetext;

CREATE DOMAIN public.titlecasetext AS text;

CREATE OR REPLACE FUNCTION "json"(public.titlecasetext) RETURNS json AS $$
  SELECT to_json(INITCAP($1::text));
$$ LANGUAGE SQL IMMUTABLE;

CREATE TABLE designers (
    id int primary key,
    name public.titlecasetext
);

CREATE TABLE videogames (
    id int primary key,
    name text,
    designer_id int
);

-- computed relationships
CREATE FUNCTION "public".computed_designers("public".videogames) RETURNS SETOF "public".designers AS $$
  SELECT * FROM "public".designers WHERE id = $1.designer_id;
$$ LANGUAGE sql STABLE ROWS 1;

CREATE FUNCTION "public".computed_designers_noset("public".videogames) RETURNS "public".designers AS $$
  SELECT * FROM "public".designers WHERE id = $1.designer_id;
$$ LANGUAGE sql STABLE;

CREATE FUNCTION "public".computed_videogames("public".designers) RETURNS SETOF "public".videogames AS $$
  SELECT * FROM "public".videogames WHERE designer_id = $1.id;
$$ LANGUAGE sql STABLE;

CREATE FUNCTION "public".getallvideogames() RETURNS SETOF "public".videogames AS $$
  SELECT * FROM "public".videogames;
$$ LANGUAGE sql STABLE;

CREATE FUNCTION "public".getalldesigners() RETURNS SETOF "public".designers AS $$
  SELECT * FROM "public".designers;
$$ LANGUAGE sql STABLE;

-- self join for computed relationships
CREATE FUNCTION "public".child_web_content("public".web_content) RETURNS SETOF "public".web_content AS $$
  SELECT * FROM "public".web_content WHERE $1.id = p_web_id;
$$ LANGUAGE sql STABLE;

CREATE FUNCTION "public".parent_web_content("public".web_content) RETURNS SETOF "public".web_content AS $$
  SELECT * FROM "public".web_content WHERE $1.p_web_id = id;
$$ LANGUAGE sql STABLE ROWS 1;

-- overriding computed rels that empty the results
CREATE FUNCTION "public".designers("public".videogames) RETURNS SETOF "public".designers AS $$
  SELECT * FROM "public".designers WHERE FALSE;
$$ LANGUAGE sql STABLE ROWS 1;

CREATE FUNCTION "public".videogames("public".designers) RETURNS SETOF "public".videogames AS $$
  SELECT * FROM "public".videogames WHERE FALSE;
$$ LANGUAGE sql STABLE;

CREATE TABLE "public".students (
    id int,
    code text,
    name text,
    primary key(id, code)
);

CREATE TABLE "public".students_info (
    id int,
    code text,
    address text,
    primary key(id, code)
);

CREATE TABLE "public".country (
    id int primary key,
    name text
);

CREATE TABLE "public".capital (
    id int primary key,
    name text,
    country_id int unique
);

CREATE FUNCTION "public".allcountries() RETURNS SETOF "public".country AS $$
  SELECT * FROM "public".country;
$$ LANGUAGE sql STABLE;

CREATE FUNCTION "public".allcapitals() RETURNS SETOF "public".capital AS $$
  SELECT * FROM "public".capital;
$$ LANGUAGE sql STABLE;

create view students_view as
select * from students;

create view students_info_view as
select * from students_info;

CREATE TABLE "public".second (
    id int primary key,
    name text
);

CREATE TABLE "public".first (
    id int primary key,
    name text,
    second_id_1 int unique,
    second_id_2 int unique
);

CREATE TABLE "public".second_1 (
    id int primary key,
    name text
);

CREATE TABLE "public".first_1 (
    id int primary key,
    name text,
    second_id_1 int unique,
    second_id_2 int unique
);

CREATE FUNCTION "public".second_1("public".first_1) RETURNS SETOF "public".second_1 AS $$
  SELECT * FROM "public".second_1 WHERE id = $1.second_id_1;
$$ LANGUAGE sql STABLE ROWS 1;

CREATE FUNCTION "public".first_1("public".second_1) RETURNS SETOF "public".first_1 AS $$
  SELECT * FROM "public".first_1 WHERE second_id_1 = $1.id;
$$ LANGUAGE sql STABLE ROWS 1;

CREATE TABLE fee (
    fee_id int primary key
);

CREATE TABLE baz (
    baz_id int primary key
);

CREATE TABLE janedoe (
    janedoe_id int primary key,
    baz_id int
);

CREATE TABLE johnsmith (
    johnsmith_id int primary key,
    fee_id int,
    baz_id int
);

create or replace function jsbaz(fee) returns setof baz as $$
    select b.*
    from baz b
    join johnsmith js on js.baz_id = b.baz_id
    where js.fee_id = $1.fee_id
$$ stable language sql;

CREATE TABLE a (
    primary key (c1, c2),
    c1 int,
    c2 bool
);

CREATE TABLE b (
    c2 bool,
    c1 int
);

create view "public".v1 as table "public".a;

create view "public".v2 as table "public".b;

CREATE TABLE with_pk1 (
    pk1 int primary key
);

CREATE TABLE with_pk2 (
    pk2 int primary key
);

create view with_multiple_pks as
  select * from with_pk1, with_pk2;

-- issue https://github.com/PostgREST/postgrest/issues/2283
create view self_recursive_view as table projects;

create or replace view self_recursive_view as table self_recursive_view;

CREATE FUNCTION "public".computed_clients("public".projects) RETURNS SETOF "public".clients ROWS 1 AS $$
  SELECT * FROM "public".clients WHERE id = $1.client_id;
$$ LANGUAGE sql STABLE;

CREATE FUNCTION "public".computed_projects("public".clients) RETURNS SETOF "public".projects ROWS 1 AS $$
  SELECT * FROM "public".projects WHERE client_id = $1.id;
$$ LANGUAGE sql STABLE;

CREATE TABLE public.i2459_simple_t1 (
    id int primary key
);

CREATE TABLE public.i2459_simple_t2 (
    t1_id int
);

create view i2459_simple_v1 as table public.i2459_simple_t1;

create view i2459_simple_v2 as
  select t1_id as t1_id1, t1_id as t1_id2 from public.i2459_simple_t2;

CREATE TABLE public.i2459_composite_t1 (
    primary key (a,b),
    a int,
    b int
);

CREATE TABLE public.i2459_composite_t2 (
    t1_a int,
    t1_b int
);

create view i2459_composite_v1 as table public.i2459_composite_t1;

create view i2459_composite_v2 as
  select t1_a as t1_a1,
         t1_b as t1_b1,
         t1_a as t1_a2,
         t1_b as t1_b2
    from public.i2459_composite_t2;

CREATE TABLE public.i2459_self_t (
    id int primary key,
    parent int,
    type text
);

create view i2459_self_v1 as
select parent.parent as grandparent,
       child.parent,
       child.id
  from public.i2459_self_t as parent
       join public.i2459_self_t as child
         on child.parent = parent.id
 where child.type = 'A';

create view i2459_self_v2 as
select parent.parent as grandparent,
       child.parent,
       child.id
  from public.i2459_self_t as parent
       join public.i2459_self_t as child
         on child.parent = parent.id
 where child.type = 'B';

CREATE TABLE public.ta (
    a1 INT PRIMARY KEY,
    a2 INT,
    UNIQUE (a1, a2)
);

CREATE TABLE public.tb (
    b1 INT,
    b2 INT
);

CREATE VIEW "public".va AS SELECT a1 FROM public.ta;

CREATE VIEW "public".vb AS SELECT b1 FROM public.tb;

CREATE TABLE "public".trash (
    id int primary key
);

CREATE TABLE "public".trash_details (
    id int primary key,
    jsonb_col jsonb
);

CREATE TABLE "public".groups (
    name text PRIMARY KEY
);

CREATE TABLE "public".yards (
    id bigint PRIMARY KEY
);

CREATE TABLE "public".group_yard (
    id bigint NOT NULL,
    group_id text NOT NULL,
    yard_id bigint NOT NULL,
    PRIMARY KEY (id, group_id, yard_id)
);

CREATE FUNCTION "public".get_yards() RETURNS SETOF "public".yards
LANGUAGE sql
AS $$
  select * from "public".yards;
$$;

CREATE TABLE "public".posters (
    id int primary key,
    name text
);

CREATE TABLE "public".subscriptions (
    subscriber int,
    subscribed int,
    primary key(subscriber, subscribed)
);

DROP DOMAIN IF EXISTS public.color;

CREATE DOMAIN public.color AS INTEGER CHECK (VALUE >= 0 AND VALUE <= 16777215);

CREATE OR REPLACE FUNCTION color(json) RETURNS public.color AS $$
  SELECT color($1 #>> '{}');
$$ LANGUAGE SQL IMMUTABLE;

CREATE OR REPLACE FUNCTION color(text) RETURNS public.color AS $$
  SELECT (('x' || lpad((CASE WHEN SUBSTRING($1::text, 1, 1) = '#' THEN SUBSTRING($1::text, 2) ELSE $1::text END), 8, '0'))::bit(32)::int)::public.color;
$$ LANGUAGE SQL IMMUTABLE;

CREATE OR REPLACE FUNCTION "json"(public.color) RETURNS json AS $$
  SELECT
    CASE WHEN $1 IS NULL THEN to_json(''::text)
    ELSE to_json('#' || lpad(upper(to_hex($1)), 6, '0'))
  END;
$$ LANGUAGE SQL IMMUTABLE;

DROP DOMAIN IF EXISTS public.isodate;

CREATE DOMAIN public.isodate AS timestamp with time zone;

CREATE OR REPLACE FUNCTION isodate(json) RETURNS public.isodate AS $$
  SELECT isodate($1 #>> '{}');
$$ LANGUAGE SQL IMMUTABLE;

CREATE OR REPLACE FUNCTION isodate(text) RETURNS public.isodate AS $$
  SELECT (replace($1, 'Z', '+00:00')::timestamp with time zone)::public.isodate;
$$ LANGUAGE SQL IMMUTABLE;

CREATE OR REPLACE FUNCTION "json"(public.isodate) RETURNS json AS $$
  SELECT to_json(replace(to_json($1)#>>'{}', '+00:00', 'Z'));
$$ LANGUAGE SQL IMMUTABLE;

DROP DOMAIN IF EXISTS public.bytea_b64;

CREATE DOMAIN public.bytea_b64 AS bytea;

CREATE OR REPLACE FUNCTION bytea_b64(json) RETURNS public.bytea_b64 AS $$
  SELECT bytea_b64($1 #>> '{}');
$$ LANGUAGE SQL IMMUTABLE;

CREATE OR REPLACE FUNCTION bytea_b64(text) RETURNS public.bytea_b64 AS $$
  -- allow unpadded base64
  SELECT decode($1 || repeat('=', 4 - (length($1) % 4)), 'base64')::public.bytea_b64;
$$ LANGUAGE SQL IMMUTABLE;

CREATE OR REPLACE FUNCTION "json"(public.bytea_b64) RETURNS json AS $$
  SELECT to_json(translate(encode($1, 'base64'), E'\n', ''));
$$ LANGUAGE SQL IMMUTABLE;

DROP DOMAIN IF EXISTS public.unixtz;

CREATE DOMAIN public.unixtz AS timestamp with time zone;

CREATE OR REPLACE FUNCTION unixtz(json) RETURNS public.unixtz AS $$
  SELECT unixtz($1 #>> '{}');
$$ LANGUAGE SQL IMMUTABLE;

CREATE OR REPLACE FUNCTION unixtz(text) RETURNS public.unixtz AS $$
  SELECT (to_timestamp($1::numeric)::public.unixtz);
$$ LANGUAGE SQL IMMUTABLE;

CREATE OR REPLACE FUNCTION "json"(public.unixtz) RETURNS json AS $$
  SELECT to_json(extract(epoch from $1)::bigint);
$$ LANGUAGE SQL IMMUTABLE;

DROP DOMAIN IF EXISTS public.monetary;

CREATE DOMAIN public.monetary AS numeric(17,2);

CREATE OR REPLACE FUNCTION monetary(json) RETURNS public.monetary AS $$
  SELECT monetary($1 #>> '{}');
$$ LANGUAGE SQL IMMUTABLE;

CREATE OR REPLACE FUNCTION monetary(text) RETURNS public.monetary AS $$
  SELECT ($1::numeric)::public.monetary;
$$ LANGUAGE SQL IMMUTABLE;

CREATE OR REPLACE FUNCTION "json"(public.monetary) RETURNS json AS $$
  SELECT to_json($1::text);
$$ LANGUAGE SQL IMMUTABLE;

CREATE TABLE datarep_todos (
    id bigint primary key,
    name text,
    label_color public.color default 0,
    due_at public.isodate default '2018-01-01'::date,
    icon_image public.bytea_b64,
    created_at public.unixtz default '2017-12-14 01:02:30'::timestamptz,
    budget public.monetary default 0
);

CREATE TABLE datarep_next_two_todos (
    id bigint primary key,
    first_item_id bigint,
    second_item_id bigint,
    name text
);

CREATE VIEW datarep_todos_computed as (
  SELECT id,
    name,
    label_color,
    due_at,
    (label_color / 2)::public.color as dark_color
  FROM datarep_todos
);

-- view's name is alphabetically before projects
create view "public".alpha_projects as
  select c.id, p.name as pro_name, c.name as cli_name
  from projects p join clients c on p.client_id = c.id;

-- view's name is alphabetically after projects
create view "public".zeta_projects as
  select c.id, p.name as pro_name, c.name as cli_name
  from projects p join clients c on p.client_id = c.id;

CREATE VIEW "public".complex_items_view AS
SELECT * FROM "public".complex_items;

ALTER VIEW "public".complex_items_view ALTER COLUMN name SET DEFAULT 'Default';

CREATE TABLE "public".tbl_w_json (
    id int,
    data json
);

CREATE TABLE "public".channels (
    id bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1) PRIMARY KEY,
    data jsonb DEFAULT '{"foo": "bar"}',
    slug text
);

CREATE FUNCTION "public".is_superuser() RETURNS boolean
LANGUAGE sql
AS $$
  select current_setting('is_superuser')::boolean;
$$;

CREATE TABLE "public".foo (
    a text,
    b text GENERATED ALWAYS AS ( case WHEN a = 'telegram' THEN 'im' WHEN a = 'proton' THEN 'email' WHEN a = 'infinity' THEN 'idea' ELSE 'bad idea' end) stored
);

create domain devil_int as int
  default 666;

CREATE TABLE evil_friends (
    id devil_int,
    name text
);

CREATE TABLE evil_friends_with_column_default (
    id devil_int default 420,
    name text
);

CREATE TABLE bets (
    id int,
    data_json json,
    data_jsonb jsonb
);

create index ASYNC bets_data_json  on bets ((data_json  ->>'contractId'));

create index ASYNC bets_data_jsonb on bets ((data_jsonb ->>'contractId'));

CREATE TABLE profiles (
    id uuid primary key,
    username text null
);

CREATE TABLE user_friend (
    id bigint primary key,
    user1 uuid,
    user2 uuid
);

CREATE TABLE status (
    id bigint primary key
);

CREATE TABLE tournaments (
    id bigint primary key,
    status bigint
);

CREATE TABLE bitchar_with_length (
    char char(5)
);

-- https://github.com/PostgREST/postgrest/issues/1586
create or replace function char_param_select(char_ char(4), char_arr char(4)[])
returns table(char_ char, char_arr char[]) as $$
  select $1, $2;
$$ language sql;

create or replace function bit_param_select(bit_ char(4), bit_arr char(4)[])
returns table(bit_ char, bit_arr char[]) as $$
  select $1, $2;
$$ language sql;

create function returns_record() returns record as $$
select * from projects limit 1;
$$ language sql;

create function returns_record_params(id int, name text) returns record as $$
select * from projects p where p.id = $1 and p.name like $2;
$$ language sql;

create function returns_setof_record() returns setof record as $$
select * from projects limit 2;
$$ language sql;

create function returns_setof_record_params(id int, name text) returns setof record as $$
select * from projects p where p.id >= $1 and p.name like $2;
$$ language sql;

CREATE TABLE table_a (
    id int primary key,
    name text
);

CREATE TABLE table_b (
    table_a_id int,
    name text
);

create function computed_rel_overload(items) returns setof items2 as $$
  select * from items2 limit 1
$$ language sql;

create function computed_rel_overload(items2) returns setof items2 as $$
  select * from items2 limit 2
$$ language sql;

CREATE TABLE "public".lines (
    id int primary key,
    name text
);

create or replace function "public".get_lines ()
returns setof "public".lines as $$
  select * from lines;
$$ language sql;

create or replace function "public".get_shop_bles ()
returns setof "public".shop_bles as $$
  select * from shop_bles;
$$ language sql;

create or replace function "public".geo2json_final (data "application/vnd.geo2+json")
returns "application/vnd.geo2+json" as $$
  select (jsonb_build_object('type', 'FeatureCollection', 'hello', 'world'))::"application/vnd.geo2+json";
$$ language sql;

create or replace function "public".lines_geojson_final (data jsonb)
returns "application/geo+json" as $$
  select jsonb_build_object(
    'type', 'FeatureCollection',
    'crs',  json_build_object(
        'type',      'name',
        'properties', json_build_object(
            'name', 'EPSG:4326'
         )
     ),
    'features', data
  )::"application/geo+json";
$$ language sql;

-- override application/vnd.pgrst.object
create or replace function "public".pgrst_obj_json_trans (state "application/vnd.pgrst.object", next anyelement)
returns "application/vnd.pgrst.object" as $$
  select null;
$$ language sql;

-- create a "text/tab-separated-values" media type
create or replace function "public".tsv_trans (state text, next "public".projects)
returns "text/tab-separated-values" as $$
  select (state || next.id::text || E'\t' || next.name || E'\t' || coalesce(next.client_id::text, '') || E'\n')::"text/tab-separated-values";
$$ language sql;

create or replace function "public".tsv_final (data "text/tab-separated-values")
returns "text/tab-separated-values" as $$
  select (E'id\tname\tclient_id\n' || data)::"text/tab-separated-values";
$$ language sql;

create or replace function "public".bom_csv_final (data "text/csv")
returns "text/csv" as $$
  select set_config('response.headers', '[{"Content-Disposition": "attachment; filename=\"lines.csv\""}]', true);
  -- EFBBBF is the BOM in UTF8 https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8
  select (convert_from (decode (E'EFBBBF', 'hex'),'UTF8') || (E'id,name,geom\n' || data))::"text/csv";
$$ language sql;

CREATE TABLE timestamps (
    t timestamp with time zone
);

CREATE TABLE project_invoices (
    id int primary key,
    invoice_total numeric,
    project_id integer
);

CREATE TABLE budget_categories (
    id int primary key,
    category_name text,
    budget_owner text,
    budget_amount numeric
);

CREATE TABLE budget_expenses (
    id int primary key,
    expense_amount numeric,
    budget_category_id integer
);

create or replace function ret_any_mt ()
returns "*/*" as $$
  select 'any'::"*/*";
$$ language sql;

create view bad_subquery as
select * from projects where id = (select id from projects);

-- custom generic mimetype
create domain "pg/outfunc" as text;

create function "public".outfunc_trans (state text, next anyelement)
returns "pg/outfunc" as $$
  select (state || next::text || E'\n')::"pg/outfunc";
$$ language sql;

-- used for manual testing
create or replace function "public".sleep(seconds double precision default 5) returns void as $$
  select pg_sleep(seconds);
$$ language sql;

-- https://github.com/PostgREST/postgrest/issues/3256
create view "public".infinite_recursion as
select * from "public".projects;

create or replace view "public".infinite_recursion as
select * from "public".infinite_recursion;

CREATE TABLE "public".infinite_inserts (
    id int,
    name text
);

CREATE TABLE factories (
    id int primary key,
    name text
);

CREATE TABLE process_categories (
    id int primary key,
    name text
);

CREATE TABLE processes (
    id int primary key,
    name text,
    factory_id int,
    category_id int
);

CREATE TABLE process_costs (
    process_id int primary key,
    cost numeric
);

CREATE TABLE supervisors (
    id int primary key,
    name text
);

CREATE TABLE process_supervisor (
    process_id int,
    supervisor_id int,
    primary key (process_id, supervisor_id)
);

CREATE TABLE surr_serial_upsert (
    id bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1) primary key,
    name text,
    extra text
);

CREATE TABLE surr_gen_default_upsert (
    id bigint generated by default AS IDENTITY (CACHE 1) primary key,
    name text,
    extra text
);

CREATE TABLE "Surr_Gen_Default_Upsert" (
    id bigint generated by default AS IDENTITY (CACHE 1) primary key,
    name text,
    extra text
);

CREATE TABLE tsearch_to_tsvector (
    text_search text,
    jsonb_search jsonb
);

create function "public".get_tsearch_to_tsvector() returns setof "public".tsearch_to_tsvector AS $$
  select * from "public".tsearch_to_tsvector;
$$ language sql;

create function "public".text_search_vector("public".tsearch_to_tsvector) returns tsvector AS $$
  select to_tsvector('simple', $1.text_search)
$$ language sql;

CREATE TABLE "public".artists (
    id int PRIMARY KEY,
    name text
);

CREATE TABLE "public".albums (
    id int PRIMARY KEY,
    title text,
    artist_id int
);

CREATE TABLE operators (
    id int primary key,
    name text,
    status jsonb
);

CREATE TABLE process_operator (
    process_id int,
    operator_id int,
    primary key (process_id, operator_id)
);

CREATE TABLE factory_buildings (
    id int primary key,
    code char(4),
    size numeric,
    "type" char(1),
    factory_id int,
    inspections jsonb
);

CREATE TABLE "public".collision_test_table (
    id integer
);

comment on table collision_test_table is 'foobarbaz';

create function "public".collision_test_func(id integer)
returns int language sql as $$
  select 1;
$$;

comment on function "public".collision_test_func(id integer) is 'fizzbuzz';

create or replace function "public".delete_items_returns_setof() returns setof items as $$
  delete from items where id <= 15 returning *; -- deletes 15 items, then return them
$$ language sql;

create or replace function "public".delete_items_returns_table() returns table(id bigint) as $$
  delete from items where id <= 15 returning *;
$$ language sql;

create or replace function "public".delete_items_returns_void() returns void as $$
  delete from items;
$$ language sql;

create function do_nothing() returns void as $_$
$_$ language sql;

create or replace function "public".get_tiobe_pls() returns setof "public".tiobe_pls as $$
  select * from "public".tiobe_pls;
$$ language sql;

CREATE TABLE places (
    id bigint primary key generated always AS IDENTITY (CACHE 1),
    name text not null
);

CREATE TABLE visits (
    id bigint primary key generated always AS IDENTITY (CACHE 1),
    place_id int not null,
    start_time timestamp,
    end_time timestamp
);

create or replace function "true"() returns boolean as $_$
  select true;
$_$ language sql;

create function uses_prepared_statements() returns bool as $$
  select count(*) > 0 from pg_catalog.pg_prepared_statements;
$$ language sql;

CREATE TABLE never_prepared (
    id int
);

create function never_uses_prepared_statements() returns bool as $$
  select count(*) = 0 from pg_catalog.pg_prepared_statements
  where statement ilike '%never_prepared%';
$$ language sql;

