#!/usr/bin/env bash
# dsql-probe.sh — Probe a live DSQL cluster for PostgreSQL constructs the
# PostgREST fixtures depend on. Prints TSV: status<TAB>name<TAB>detail
set -uo pipefail
HOST="${DSQL_ENDPOINT:?set DSQL_ENDPOINT}"
REGION="${REGION_NAME:-us-east-1}"
PGPASSWORD="$(aws dsql generate-db-connect-admin-auth-token --region "$REGION" --hostname "$HOST" --expires-in 3600)"
export PGPASSWORD PGSSLMODE=require
q() { psql -h "$HOST" -U admin -d postgres -p 5432 -v ON_ERROR_STOP=1 -qtAX -c "$1" 2>&1; }
probe() {
  local name="$1" sql="$2" out
  if out="$(q "$sql")"; then printf 'OK\t%s\t%s\n' "$name" "$(echo "$out" | tr '\n' ' ' | cut -c1-140)"
  else printf 'FAIL\t%s\t%s\n' "$name" "$(echo "$out" | grep -iEm1 'error|not supported|unsupported' | cut -c1-200)"; fi
}
q 'DROP TABLE IF EXISTS p_parent CASCADE; DROP TABLE IF EXISTS p_child CASCADE;' >/dev/null
probe base_table          'CREATE TABLE p_parent(id int PRIMARY KEY, name text); SELECT 1'
probe insert_select       "INSERT INTO p_parent VALUES (1,'a'),(2,'b'); SELECT count(*) FROM p_parent"
probe foreign_key         'CREATE TABLE p_child(id int PRIMARY KEY, pid int REFERENCES p_parent(id)); SELECT 1'
probe fk_alter_add        'CREATE TABLE p_c2(id int PRIMARY KEY, pid int); ALTER TABLE p_c2 ADD CONSTRAINT fk2 FOREIGN KEY (pid) REFERENCES p_parent(id); SELECT 1'
probe check_constraint    'CREATE TABLE p_chk(id int PRIMARY KEY, n int CHECK (n > 0)); SELECT 1'
probe unique_constraint   'CREATE TABLE p_uq(id int PRIMARY KEY, e text UNIQUE); SELECT 1'
probe serial_identity     'CREATE TABLE p_ident(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, t text); SELECT 1'
probe serial_keyword      'CREATE TABLE p_serial(id serial PRIMARY KEY, t text); SELECT 1'
probe sequence            'CREATE SEQUENCE p_seq; SELECT 1'
probe view                'CREATE VIEW p_view AS SELECT id, name FROM p_parent; SELECT count(*) FROM p_view'
probe matview             'CREATE MATERIALIZED VIEW p_mv AS SELECT id FROM p_parent; SELECT 1'
probe function_sql        "CREATE FUNCTION p_fn_sql(a int) RETURNS int LANGUAGE sql AS 'SELECT a + 1'; SELECT p_fn_sql(1)"
probe function_plpgsql    "CREATE FUNCTION p_fn_pl(a int) RETURNS int LANGUAGE plpgsql AS \$\$BEGIN RETURN a+1; END\$\$; SELECT p_fn_pl(1)"
probe function_setof      "CREATE FUNCTION p_fn_set() RETURNS SETOF p_parent LANGUAGE sql AS 'SELECT * FROM p_parent'; SELECT count(*) FROM p_fn_set()"
probe function_table      "CREATE FUNCTION p_fn_tbl() RETURNS TABLE(x int) LANGUAGE sql AS 'SELECT 1'; SELECT * FROM p_fn_tbl()"
probe domain              'CREATE DOMAIN p_dom AS text CHECK (VALUE <> \x27\x27); SELECT 1'
probe enum_type           "CREATE TYPE p_enum AS ENUM ('a','b'); SELECT 1"
probe composite_type      'CREATE TYPE p_comp AS (a int, b text); SELECT 1'
probe trigger             "CREATE FUNCTION p_trg() RETURNS trigger LANGUAGE plpgsql AS \$\$BEGIN RETURN NEW; END\$\$; CREATE TRIGGER t1 BEFORE INSERT ON p_parent FOR EACH ROW EXECUTE FUNCTION p_trg(); SELECT 1"
probe rls_enable          'ALTER TABLE p_parent ENABLE ROW LEVEL SECURITY; SELECT 1'
probe rls_policy          'CREATE POLICY pol ON p_parent USING (true); SELECT 1'
probe create_role         'CREATE ROLE p_role_test; SELECT 1'
probe set_role            'SET LOCAL ROLE TO postgres; SELECT 1'
probe grant               'GRANT SELECT ON p_parent TO PUBLIC; SELECT 1'
probe create_schema       'CREATE SCHEMA p_other; SELECT 1'
probe temp_table          'CREATE TEMP TABLE p_tmp(id int); SELECT 1'
probe truncate            'TRUNCATE p_parent; SELECT 1'
probe lateral_json_agg    "SELECT json_agg(x) FROM (SELECT 1 AS a) x"
probe lateral_join        'SELECT p.id FROM p_parent p, LATERAL (SELECT 1) l'
probe cte                 'WITH c AS (SELECT 1 AS x) SELECT x FROM c'
probe window_fn           'SELECT row_number() OVER () FROM p_parent'
probe jsonb_ops           "SELECT '{\"a\":1}'::jsonb @> '{\"a\":1}'::jsonb, '{\"a\":1}'::jsonb->>'a'"
probe array_contains      "SELECT ARRAY[1,2] @> ARRAY[1]"
probe tsvector_fts        "SELECT to_tsvector('english','hello world') @@ to_tsquery('english','hello')"
probe gin_index           'CREATE INDEX ON p_parent USING gin (name gin_trgm_ops); SELECT 1'
probe range_type          "SELECT int4range(1,5) @> 3"
probe regex_match         "SELECT 'abc' ~ '^a'"
probe generated_column    'CREATE TABLE p_gen(id int PRIMARY KEY, a int, b int GENERATED ALWAYS AS (a*2) STORED); SELECT 1'
probe partition_table     'CREATE TABLE p_part(id int, d date) PARTITION BY RANGE (d); SELECT 1'
probe explain             'EXPLAIN SELECT * FROM p_parent'
probe explain_analyze     'EXPLAIN (ANALYZE) SELECT * FROM p_parent'
probe savepoint           'BEGIN; SAVEPOINT s1; ROLLBACK TO s1; COMMIT'
probe extension_pgcrypto  'CREATE EXTENSION IF NOT EXISTS pgcrypto; SELECT 1'
probe upsert_on_conflict  "INSERT INTO p_parent VALUES (1,'z') ON CONFLICT (id) DO UPDATE SET name='z'; SELECT 1"
probe returning           "INSERT INTO p_parent VALUES (9,'r') RETURNING id"
probe catalog_pg_class    "SELECT count(*) FROM pg_catalog.pg_class WHERE relkind='r'"
probe catalog_pg_proc     'SELECT count(*) FROM pg_catalog.pg_proc'
probe catalog_pg_constr   "SELECT count(*) FROM pg_catalog.pg_constraint WHERE contype='f'"
