// embedding.test.mjs — Integration tests for resource embedding
//
// Skipped unless TEST_DATABASE_URL is set:
//   TEST_DATABASE_URL=postgresql://postgres:pass@localhost:5433/postgres \
//     node --test test/integration/embedding.test.mjs

import { describe, it, before, after, beforeEach } from 'node:test';
import assert from 'node:assert/strict';
import pg from 'pg';
import { createPgrest } from '../../src/index.mjs';
import { JWT_SECRET, makeEvent } from './helpers.mjs';

const DATABASE_URL = process.env.TEST_DATABASE_URL;

export const EMBEDDING_SCHEMA_SQL = `
  DROP TABLE IF EXISTS order_product_notes CASCADE;
  DROP TABLE IF EXISTS order_items CASCADE;
  DROP TABLE IF EXISTS products CASCADE;
  DROP TABLE IF EXISTS orders CASCADE;
  DROP TABLE IF EXISTS customers CASCADE;
  DROP TABLE IF EXISTS addresses CASCADE;

  CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)
      PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT
  );

  CREATE TABLE addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)
      PRIMARY KEY,
    street TEXT NOT NULL,
    city TEXT NOT NULL
  );

  CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)
      PRIMARY KEY,
    customer_id BIGINT REFERENCES customers(id),
    billing_address_id BIGINT REFERENCES addresses(id),
    shipping_address_id BIGINT REFERENCES addresses(id),
    amount NUMERIC(10,2) NOT NULL
  );

  CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)
      PRIMARY KEY,
    name TEXT NOT NULL,
    price NUMERIC(10,2) NOT NULL
  );

  CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)
      PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id),
    product_id BIGINT REFERENCES products(id),
    quantity INT NOT NULL DEFAULT 1
  );

  CREATE TABLE order_product_notes (
    order_id BIGINT REFERENCES orders(id),
    product_id BIGINT REFERENCES products(id),
    note TEXT NOT NULL,
    PRIMARY KEY (order_id, product_id)
  );
`;

// Seed includes:
//   - Customer 3 (Charlie) with no orders — for empty-array test
//   - Order 4 with NULL customer_id — for null-FK and inner-join tests
//   - Order 2 with NULL billing/shipping address FKs
export const EMBEDDING_SEED_SQL = `
  DELETE FROM order_product_notes;
  DELETE FROM order_items;
  DELETE FROM orders;
  DELETE FROM products;
  DELETE FROM customers;
  DELETE FROM addresses;

  INSERT INTO customers (id, name, email) VALUES
    (1, 'Alice', 'alice@test.com'),
    (2, 'Bob', 'bob@test.com'),
    (3, 'Charlie', 'charlie@test.com');

  INSERT INTO addresses (id, street, city) VALUES
    (1, '123 Billing St', 'New York'),
    (2, '456 Shipping Ave', 'Boston');

  INSERT INTO orders (id, customer_id, billing_address_id,
      shipping_address_id, amount) VALUES
    (1, 1, 1, 2, 99.00),
    (2, 1, NULL, NULL, 50.00),
    (3, 2, 1, 1, 75.00),
    (4, NULL, NULL, NULL, 25.00);

  INSERT INTO products (id, name, price) VALUES
    (1, 'Widget', 9.99),
    (2, 'Gadget', 19.99),
    (3, 'Doohickey', 29.99);

  INSERT INTO order_items (id, order_id, product_id, quantity) VALUES
    (1, 1, 1, 2),
    (2, 1, 2, 1),
    (3, 3, 1, 5);

  SELECT setval(pg_get_serial_sequence('customers', 'id'),
    (SELECT MAX(id) FROM customers));
  SELECT setval(pg_get_serial_sequence('addresses', 'id'),
    (SELECT MAX(id) FROM addresses));
  SELECT setval(pg_get_serial_sequence('orders', 'id'),
    (SELECT MAX(id) FROM orders));
  SELECT setval(pg_get_serial_sequence('products', 'id'),
    (SELECT MAX(id) FROM products));
  SELECT setval(pg_get_serial_sequence('order_items', 'id'),
    (SELECT MAX(id) FROM order_items));

  DELETE FROM order_product_notes;
  INSERT INTO order_product_notes
      (order_id, product_id, note) VALUES
    (1, 1, 'Gift wrap'),
    (1, 2, 'Express'),
    (3, 1, 'Bulk order');
`;

export const EMBEDDING_DROP_SQL = `
  DROP TABLE IF EXISTS order_product_notes CASCADE;
  DROP TABLE IF EXISTS order_items CASCADE;
  DROP TABLE IF EXISTS products CASCADE;
  DROP TABLE IF EXISTS orders CASCADE;
  DROP TABLE IF EXISTS customers CASCADE;
  DROP TABLE IF EXISTS addresses CASCADE;
`;

describe('resource embedding', { skip: !DATABASE_URL }, () => {
  let pool;
  let pgrest;

  before(async () => {
    pool = new pg.Pool({ connectionString: DATABASE_URL });
    await pool.query(EMBEDDING_SCHEMA_SQL);
    pgrest = createPgrest({
      database: { connectionString: DATABASE_URL },
      jwtSecret: JWT_SECRET,
      auth: false,
    });
  });

  beforeEach(async () => {
    await pool.query(EMBEDDING_SEED_SQL);
    await pgrest.rest(makeEvent({
      method: 'POST', path: '/rest/v1/_refresh',
    }));
  });

  after(async () => {
    await pool.query(EMBEDDING_DROP_SQL);
    await pool.end();
  });

  describe('many-to-one embed', () => {
    it('embeds parent as JSON object', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/orders',
        query: { select: 'id,amount,customers(name,email)' },
      }));
      assert.equal(res.statusCode, 200);
      const rows = JSON.parse(res.body);
      const order1 = rows.find(r => Number(r.id) === 1);
      assert.ok(order1, 'order 1 should be in results');
      assert.ok('customers' in order1,
        'order should have customers key');
      assert.ok(
        !Array.isArray(order1.customers),
        'customers should be an object, not an array',
      );
      assert.deepStrictEqual(order1.customers, {
        name: 'Alice', email: 'alice@test.com',
      });
    });
  });

  describe('many-to-one null FK', () => {
    it('returns null for NULL billing_address_id', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/orders',
        query: {
          select: 'id,addresses!billing_address_id(street)',
          id: 'eq.2',
        },
      }));
      assert.equal(res.statusCode, 200);
      const rows = JSON.parse(res.body);
      assert.equal(rows.length, 1);
      assert.equal(Number(rows[0].id), 2);
      assert.strictEqual(rows[0].addresses, null,
        'billing address embed should be null for NULL FK');
    });

    it('returns null for NULL customer_id', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/orders',
        query: {
          select: 'id,customers(name)',
          id: 'eq.4',
        },
      }));
      assert.equal(res.statusCode, 200);
      const rows = JSON.parse(res.body);
      assert.equal(rows.length, 1);
      assert.strictEqual(rows[0].customers, null,
        'customers embed should be null for NULL FK');
    });
  });

  describe('one-to-many embed', () => {
    it('embeds children as JSON array', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/customers',
        query: { select: 'id,orders(id,amount)' },
      }));
      assert.equal(res.statusCode, 200);
      const rows = JSON.parse(res.body);
      const alice = rows.find(r => Number(r.id) === 1);
      const bob = rows.find(r => Number(r.id) === 2);
      assert.ok(alice, 'Alice should be in results');
      assert.ok(bob, 'Bob should be in results');
      assert.ok(Array.isArray(alice.orders),
        'orders should be an array');
      assert.equal(alice.orders.length, 2,
        'Alice has 2 orders');
      assert.equal(bob.orders.length, 1,
        'Bob has 1 order');
    });

    it('returns empty array for customer with no orders',
      async () => {
        const res = await pgrest.rest(makeEvent({
          path: '/rest/v1/customers',
          query: {
            select: 'id,orders(id)',
            name: 'eq.Charlie',
          },
        }));
        assert.equal(res.statusCode, 200);
        const rows = JSON.parse(res.body);
        assert.equal(rows.length, 1);
        assert.deepStrictEqual(rows[0].orders, [],
          'orders should be empty array, not null');
      },
    );
  });

  describe('wildcard parent and child', () => {
    it('expands * on both parent and embedded table', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/orders',
        query: { select: '*,customers(*)' },
      }));
      assert.equal(res.statusCode, 200);
      const rows = JSON.parse(res.body);
      const order1 = rows.find(r => Number(r.id) === 1);
      assert.ok(order1);
      // Parent should have all order columns
      for (const col of ['id', 'customer_id',
        'billing_address_id', 'shipping_address_id', 'amount']) {
        assert.ok(col in order1,
          `order should have column ${col}`);
      }
      // Embedded customers should have all customer columns
      assert.ok(order1.customers);
      for (const col of ['id', 'name', 'email']) {
        assert.ok(col in order1.customers,
          `embedded customer should have column ${col}`);
      }
    });
  });

  describe('aliased embed', () => {
    it('uses alias as JSON key', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/orders',
        query: { select: 'id,buyer:customers(name)' },
      }));
      assert.equal(res.statusCode, 200);
      const rows = JSON.parse(res.body);
      const order1 = rows.find(r => Number(r.id) === 1);
      assert.ok(order1);
      assert.ok('buyer' in order1,
        'should use alias "buyer" as key');
      assert.ok(!('customers' in order1),
        'should not have "customers" key when aliased');
      assert.ok(order1.buyer.name,
        'buyer should have name property');
    });
  });

  describe('nested embed (2 levels)', () => {
    it('nests embeds within embeds', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/orders',
        query: {
          select: 'id,order_items(id,products(name))',
        },
      }));
      assert.equal(res.statusCode, 200);
      const rows = JSON.parse(res.body);
      const order1 = rows.find(r => Number(r.id) === 1);
      assert.ok(order1);
      assert.ok(Array.isArray(order1.order_items),
        'order_items should be an array');
      assert.equal(order1.order_items.length, 2,
        'order 1 has 2 items');
      for (const item of order1.order_items) {
        assert.ok(item.products,
          'each item should have products embed');
        assert.ok(item.products.name,
          'products embed should have name');
      }
      const names = order1.order_items.map(
        i => i.products.name);
      assert.ok(names.includes('Widget'));
      assert.ok(names.includes('Gadget'));
    });
  });

  describe('inner join', () => {
    it('one-to-many: excludes parents without children',
      async () => {
        // Charlie (id=3) has no orders — should be excluded
        const res = await pgrest.rest(makeEvent({
          path: '/rest/v1/customers',
          query: { select: 'id,name,orders!inner(id)' },
        }));
        assert.equal(res.statusCode, 200);
        const rows = JSON.parse(res.body);
        for (const row of rows) {
          assert.ok(Array.isArray(row.orders),
            'orders should be array');
          assert.ok(row.orders.length > 0,
            'all returned customers should have orders');
        }
        const names = rows.map(r => r.name);
        assert.ok(!names.includes('Charlie'),
          'Charlie (no orders) should not appear');
      },
    );

    it('many-to-one: excludes rows with NULL FK', async () => {
      // Order 4 has NULL customer_id — should be excluded
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/orders',
        query: { select: 'id,customers!inner(name)' },
      }));
      assert.equal(res.statusCode, 200);
      const rows = JSON.parse(res.body);
      const ids = rows.map(r => Number(r.id));
      assert.ok(!ids.includes(4),
        'order with NULL customer_id should be excluded');
      for (const row of rows) {
        assert.ok(row.customers,
          'all returned orders should have non-null customers');
      }
    });
  });

  describe('disambiguation with !hint', () => {
    it('resolves ambiguous FKs with column name hints',
      async () => {
        const res = await pgrest.rest(makeEvent({
          path: '/rest/v1/orders',
          query: {
            select: '*,billing:addresses!billing_address_id(*),'
              + 'shipping:addresses!shipping_address_id(*)',
          },
        }));
        assert.equal(res.statusCode, 200);
        const rows = JSON.parse(res.body);
        const order1 = rows.find(r => Number(r.id) === 1);
        const order2 = rows.find(r => Number(r.id) === 2);
        assert.ok(order1);
        assert.ok(order2);
        // Order 1: billing=address 1, shipping=address 2
        assert.ok('billing' in order1);
        assert.ok('shipping' in order1);
        assert.equal(order1.billing.street, '123 Billing St');
        assert.equal(order1.shipping.street,
          '456 Shipping Ave');
        // Order 2: both address FKs are NULL
        assert.strictEqual(order2.billing, null);
        assert.strictEqual(order2.shipping, null);
      },
    );
  });

  describe('error: no relationship found (PGRST200)', () => {
    it('returns 400 with PGRST200 for unknown embed',
      async () => {
        const res = await pgrest.rest(makeEvent({
          path: '/rest/v1/orders',
          query: { select: 'id,nonexistent(name)' },
        }));
        assert.equal(res.statusCode, 400);
        const body = JSON.parse(res.body);
        assert.equal(body.code, 'PGRST200');
        assert.ok(body.message.includes('orders'),
          'error should reference parent table');
        assert.ok(body.message.includes('nonexistent'),
          'error should reference embed name');
      },
    );
  });

  describe('error: ambiguous relationship (PGRST201)', () => {
    it('returns 300 with PGRST201 when no hint provided',
      async () => {
        // orders has two FKs to addresses (billing + shipping)
        const res = await pgrest.rest(makeEvent({
          path: '/rest/v1/orders',
          query: { select: 'id,addresses(street)' },
        }));
        assert.equal(res.statusCode, 300);
        const body = JSON.parse(res.body);
        assert.equal(body.code, 'PGRST201');
        assert.ok(Array.isArray(body.details),
          'details should be an array');
        assert.equal(body.details.length, 2,
          'should list 2 ambiguous relationships');
        assert.ok(body.hint,
          'should include hint text');
      },
    );
  });

  describe('error: column not found in embed (PGRST204)', () => {
    it('returns 400 with PGRST204 for bad embed column',
      async () => {
        const res = await pgrest.rest(makeEvent({
          path: '/rest/v1/orders',
          query: { select: 'id,customers(nonexistent_col)' },
        }));
        assert.equal(res.statusCode, 400);
        const body = JSON.parse(res.body);
        assert.equal(body.code, 'PGRST204');
        // The error must reference 'nonexistent_col' as the
        // column and 'customers' as the table where lookup
        // failed — NOT 'orders' (the parent). If the message
        // says "does not exist in 'orders'", the embed was not
        // parsed and we hit the wrong code path.
        assert.ok(body.message.includes('nonexistent_col'),
          'error should reference the bad column');
        assert.ok(
          body.message.includes("in 'customers'"),
          'error should say column is missing in the embed '
          + "table 'customers', not the parent table 'orders'",
        );
      },
    );
  });

  describe('space handling in select', () => {
    it('trims spaces in embed syntax', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/orders',
        query: { select: 'id, customers(name, email)' },
      }));
      assert.equal(res.statusCode, 200);
      const rows = JSON.parse(res.body);
      const order1 = rows.find(r => Number(r.id) === 1);
      assert.ok(order1);
      assert.ok('customers' in order1);
      assert.deepStrictEqual(order1.customers, {
        name: 'Alice', email: 'alice@test.com',
      });
    });
  });

  describe('backward compatibility', () => {
    it('flat select unchanged', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/orders',
        query: { select: 'id,amount' },
      }));
      assert.equal(res.statusCode, 200);
      const rows = JSON.parse(res.body);
      assert.ok(rows.length > 0);
      for (const row of rows) {
        assert.ok('id' in row);
        assert.ok('amount' in row);
        assert.equal(Object.keys(row).length, 2,
          'should only have id and amount');
      }
    });

    it('wildcard select unchanged', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/orders',
        query: { select: '*' },
      }));
      assert.equal(res.statusCode, 200);
      const rows = JSON.parse(res.body);
      assert.ok(rows.length > 0);
      for (const row of rows) {
        assert.ok('id' in row);
        assert.ok('amount' in row);
        assert.ok('customer_id' in row);
        // No embedding keys should be present
        assert.ok(!('customers' in row));
      }
    });

    it('no select param returns all columns', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/orders',
      }));
      assert.equal(res.statusCode, 200);
      const rows = JSON.parse(res.body);
      assert.ok(rows.length > 0);
      for (const row of rows) {
        assert.ok('id' in row);
        assert.ok('amount' in row);
        assert.ok('customer_id' in row);
      }
    });
  });

  describe('filters with embeds', () => {
    it('applies filters alongside embeds', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/orders',
        query: {
          select: 'id,customers(name)',
          amount: 'gt.50',
        },
      }));
      assert.equal(res.statusCode, 200);
      const rows = JSON.parse(res.body);
      assert.ok(rows.length > 0);
      for (const row of rows) {
        assert.ok(Number(row.id) !== 2,
          'order 2 (amount=50) excluded by gt.50');
        assert.ok(Number(row.id) !== 4,
          'order 4 (amount=25) excluded by gt.50');
        assert.ok('customers' in row,
          'each row should have customers embed');
      }
    });
  });

  describe('return=representation with embeds', () => {
    it('POST returns embedded data', async () => {
      const res = await pgrest.rest(makeEvent({
        method: 'POST',
        path: '/rest/v1/orders',
        body: { customer_id: 2, amount: 200.00 },
        headers: { Prefer: 'return=representation' },
        query: { select: 'id,amount,customers(name)' },
      }));
      assert.equal(res.statusCode, 201);
      const rows = JSON.parse(res.body);
      assert.ok(rows.length > 0);
      const row = rows[0];
      assert.ok('customers' in row,
        'response should include embedded customers');
      assert.equal(row.customers.name, 'Bob');
      assert.equal(Number(row.amount), 200);
    });

    it('PATCH returns embedded data', async () => {
      const res = await pgrest.rest(makeEvent({
        method: 'PATCH',
        path: '/rest/v1/orders',
        query: {
          id: 'eq.1',
          select: 'id,amount,customers(name)',
        },
        body: { amount: 999.00 },
        headers: { Prefer: 'return=representation' },
      }));
      assert.equal(res.statusCode, 200);
      const rows = JSON.parse(res.body);
      assert.ok(rows.length > 0);
      const row = rows[0];
      assert.equal(Number(row.amount), 999);
      assert.ok('customers' in row,
        'response should include embedded customers');
    });

    it('DELETE with embeds returns empty — re-SELECT '
      + 'cannot find deleted rows (known limitation)',
    async () => {
      // DELETE uses RETURNING * to get flat rows, then
      // re-SELECT queries by PK to attach embeds. But
      // the row is already deleted, so re-SELECT returns
      // zero rows. This is a known limitation: embeds
      // with return=representation do not work for DELETE
      // because the re-SELECT happens after the row is
      // gone.
      //
      // Use order 2 (Alice, amount=50.00) which has no
      // child rows in order_items or order_product_notes,
      // avoiding FK constraint violations.
      const res = await pgrest.rest(makeEvent({
        method: 'DELETE',
        path: '/rest/v1/orders',
        query: {
          id: 'eq.2',
          select: 'id,customers(name)',
        },
        headers: { Prefer: 'return=representation' },
      }));
      assert.equal(res.statusCode, 200);
      const rows = JSON.parse(res.body);
      // The re-SELECT finds nothing because the row was
      // already deleted. The response is an empty array.
      assert.equal(rows.length, 0,
        'DELETE re-SELECT returns empty because the '
        + 'deleted row no longer exists');
      // Verify the row was actually deleted
      const check = await pool.query(
        'SELECT 1 FROM orders WHERE id = 2');
      assert.equal(check.rows.length, 0,
        'order 2 should be deleted');
    });
  });

  describe('composite PK re-SELECT', () => {
    it('returns exactly the inserted rows for composite PK',
      async () => {
        const res = await pgrest.rest(makeEvent({
          method: 'POST',
          path: '/rest/v1/order_product_notes',
          body: { order_id: 1, product_id: 3, note: 'Test' },
          headers: { Prefer: 'return=representation' },
          query: {
            select: 'order_id,product_id,note,'
              + 'orders(id,amount)',
          },
        }));
        assert.equal(res.statusCode, 201);
        const rows = JSON.parse(res.body);
        // Should return exactly 1 row (the inserted row),
        // not additional rows sharing order_id=1
        assert.equal(rows.length, 1,
          'should return exactly the inserted row');
        assert.equal(Number(rows[0].order_id), 1);
        assert.equal(Number(rows[0].product_id), 3);
        assert.equal(rows[0].note, 'Test');
        assert.ok('orders' in rows[0],
          'should include embedded orders data');
      },
    );
  });

  describe('parser validation', () => {
    it('alias injection attempt returns 400', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/orders',
        query: { select: "id,x'bad:customers(name)" },
      }));
      assert.equal(res.statusCode, 400);
      const body = JSON.parse(res.body);
      assert.equal(body.code, 'PGRST100');
    });
  });

  describe('ordering and pagination with embeds', () => {
    it('order and limit work alongside embeds', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/orders',
        query: {
          select: 'id,amount,customers(name)',
          order: 'amount.desc',
          limit: '2',
        },
      }));
      assert.equal(res.statusCode, 200);
      const rows = JSON.parse(res.body);
      assert.equal(rows.length, 2,
        'should return exactly 2 rows');
      // Seed amounts: 99.00, 50.00, 75.00, 25.00
      // desc order: 99, 75, 50, 25 -> top 2: 99, 75
      assert.ok(
        Number(rows[0].amount) >= Number(rows[1].amount),
        'rows should be ordered by amount descending');
      for (const row of rows) {
        assert.ok('customers' in row,
          'each row should have customers embed');
      }
    });

    it('offset with embeds skips correct rows', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/orders',
        query: {
          select: 'id,amount,customers(name)',
          order: 'amount.desc',
          limit: '2',
          offset: '2',
        },
      }));
      assert.equal(res.statusCode, 200);
      const rows = JSON.parse(res.body);
      assert.equal(rows.length, 2,
        'should return 2 rows after offset');
      // desc order with offset 2: 50.00, 25.00
      for (const row of rows) {
        assert.ok('customers' in row,
          'each row should have customers embed');
      }
    });
  });

  describe('authorization on embeds', () => {
    // The default Cedar policies distinguish by user_id row
    // ownership, not by table. The embedding tables lack user_id
    // columns, so per-table restriction testing requires custom
    // Cedar policies that do not exist in the test harness.
    //
    // Skip until Cedar supports per-table read restrictions
    // independent of row ownership.
    it('silently excludes unauthorized embeds', {
      skip: 'requires per-table Cedar policy setup',
    }, async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/orders',
        query: { select: 'id,customers(name)' },
        role: 'authenticated',
        userId: 'test-user',
        email: 'test@test.com',
      }));
      assert.equal(res.statusCode, 200);
      const rows = JSON.parse(res.body);
      assert.ok(rows.length > 0,
        'orders should be returned');
      for (const row of rows) {
        assert.strictEqual(row.customers, null,
          'customers embed should be null (unauthorized)');
      }
    });

    it('embed authz filters applied correctly', {
      skip: 'requires Cedar policy fixtures for '
        + 'per-table parameterized conditions',
    }, async () => {
      // Given Cedar policies restricting both parent
      // and child tables with parameterized conditions
      // When querying with embeds and filters
      // Then parent rows are filtered by parent authz
      // AND child embeds are filtered by child authz
    });

    it('count=exact respects authz with embeds', {
      skip: 'requires Cedar policy fixtures for '
        + 'per-table parameterized conditions',
    }, async () => {
      // Given a Cedar policy restricting user to own rows
      // When GET with Prefer: count=exact and embeds
      // Then Content-Range count matches authorized rows
    });
  });
});
