// logical-operators.test.mjs — Integration tests for logical operators
//
// Skipped unless TEST_DATABASE_URL is set:
//   TEST_DATABASE_URL=postgresql://postgres:pass@localhost:5433/postgres \
//     node --test test/integration/logical-operators.test.mjs

import { describe, it, before, after, beforeEach } from 'node:test';
import assert from 'node:assert/strict';
import pg from 'pg';
import { createPgrest } from '../../src/index.mjs';
import { JWT_SECRET, makeEvent } from './helpers.mjs';

const DATABASE_URL = process.env.TEST_DATABASE_URL;

const SCHEMA_SQL = `
  DROP TABLE IF EXISTS orders CASCADE;
  DROP TABLE IF EXISTS customers CASCADE;
  DROP TABLE IF EXISTS people CASCADE;

  CREATE TABLE people (
    id BIGINT PRIMARY KEY,
    name TEXT NOT NULL,
    age INT NOT NULL,
    status TEXT NOT NULL,
    priority TEXT NOT NULL,
    assigned_to TEXT,
    featured BOOLEAN NOT NULL
  );

  CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)
      PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT
  );

  CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)
      PRIMARY KEY,
    customer_id BIGINT REFERENCES customers(id),
    amount NUMERIC(10,2) NOT NULL
  );
`;

// Seed: people data designed so every test case is
// distinguishable.
//
//   age < 18:  Alice (15), Frank (12)
//   age > 65:  Charlie (70)
//   status=vip: Bob (25)
//   age 18-25: Bob (25), Diana (20)
//   status cancelled|refunded: Charlie, Eve
//   assigned_to IS NULL: Bob, Diana
//   status=active: Alice, Diana, Frank
//   featured=true: Alice, Charlie, Eve
//   priority=high: Alice, Charlie, Eve
const SEED_SQL = `
  DELETE FROM orders;
  DELETE FROM customers;
  DELETE FROM people;

  INSERT INTO people (id, name, age, status, priority,
      assigned_to, featured) VALUES
    (1, 'Alice',   15, 'active',    'high',   'bob',   true),
    (2, 'Bob',     25, 'vip',       'low',    NULL,    false),
    (3, 'Charlie', 70, 'cancelled', 'high',   'alice', true),
    (4, 'Diana',   20, 'active',    'medium', NULL,    false),
    (5, 'Eve',     30, 'refunded',  'high',   'bob',   true),
    (6, 'Frank',   12, 'active',    'low',    'alice', false);

  INSERT INTO customers (id, name, email) VALUES
    (1, 'Cust_Alice', 'calice@test.com'),
    (2, 'Cust_Bob',   'cbob@test.com');

  SELECT setval(pg_get_serial_sequence('customers', 'id'),
    (SELECT MAX(id) FROM customers));

  INSERT INTO orders (id, customer_id, amount) VALUES
    (1, 1, 99.00),
    (2, 1, 50.00),
    (3, 2, 75.00),
    (4, NULL, 25.00);

  SELECT setval(pg_get_serial_sequence('orders', 'id'),
    (SELECT MAX(id) FROM orders));
`;

const DROP_SQL = `
  DROP TABLE IF EXISTS orders CASCADE;
  DROP TABLE IF EXISTS customers CASCADE;
  DROP TABLE IF EXISTS people CASCADE;
`;

/** Extract sorted names from a 200 JSON response. */
function names(res) {
  assert.equal(res.statusCode, 200);
  return JSON.parse(res.body).map(r => r.name).sort();
}

describe('logical operators', { skip: !DATABASE_URL }, () => {
  let pool;
  let pgrest;

  before(async () => {
    pool = new pg.Pool({ connectionString: DATABASE_URL });
    await pool.query(SCHEMA_SQL);
    pgrest = createPgrest({
      database: { connectionString: DATABASE_URL },
      jwtSecret: JWT_SECRET,
      auth: false,
    });
  });

  beforeEach(async () => {
    await pool.query(SEED_SQL);
    await pgrest.rest(makeEvent({
      method: 'POST', path: '/rest/v1/_refresh',
    }));
  });

  after(async () => {
    await pool.query(DROP_SQL);
    await pool.end();
  });

  // --- Basic logical operators ---

  describe('basic or', () => {
    it('age.lt.18 OR age.gt.65', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/people',
        query: { or: '(age.lt.18,age.gt.65)' },
      }));
      assert.deepStrictEqual(names(res),
        ['Alice', 'Charlie', 'Frank']);
    });
  });

  describe('basic and (explicit)', () => {
    it('status.eq.active AND priority.eq.high', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/people',
        query: { and: '(status.eq.active,priority.eq.high)' },
      }));
      assert.deepStrictEqual(names(res), ['Alice']);
    });
  });

  describe('not.or', () => {
    it('excludes cancelled and refunded', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/people',
        query: {
          'not.or': '(status.eq.cancelled,status.eq.refunded)',
        },
      }));
      assert.deepStrictEqual(names(res),
        ['Alice', 'Bob', 'Diana', 'Frank']);
    });
  });

  describe('not.and', () => {
    it('excludes rows matching all conditions', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/people',
        query: {
          'not.and': '(status.eq.active,priority.eq.high)',
        },
      }));
      assert.deepStrictEqual(names(res),
        ['Bob', 'Charlie', 'Diana', 'Eve', 'Frank']);
    });
  });

  // --- Nested logical operators ---

  describe('nested and inside or', () => {
    it('returns vip OR age 18-25', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/people',
        query: {
          or: '(status.eq.vip,and(age.gte.18,age.lte.25))',
        },
      }));
      assert.deepStrictEqual(names(res), ['Bob', 'Diana']);
    });
  });

  describe('nested or inside and', () => {
    it('featured AND (active OR vip)', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/people',
        query: {
          and: '(featured.is.true,'
            + 'or(status.eq.active,status.eq.vip))',
        },
      }));
      assert.deepStrictEqual(names(res), ['Alice']);
    });
  });

  describe('three levels of nesting', () => {
    it('or(name, and(status, or(age, priority)))',
      async () => {
        const res = await pgrest.rest(makeEvent({
          path: '/rest/v1/people',
          query: {
            or: '(name.eq.Alice,and(status.eq.active,'
              + 'or(age.lt.18,priority.eq.medium)))',
          },
        }));
        assert.deepStrictEqual(names(res),
          ['Alice', 'Diana', 'Frank']);
      });
  });

  describe('not.and nested inside or', () => {
    it('age=25 OR NOT(age 18-30)', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/people',
        query: {
          or: '(age.eq.25,not.and(age.gte.18,age.lte.30))',
        },
      }));
      assert.deepStrictEqual(names(res),
        ['Alice', 'Bob', 'Charlie', 'Frank']);
    });
  });

  // --- Special operators inside logical groups ---

  describe('in operator inside or (comma handling)', () => {
    it('status in (vip,cancelled) OR medium priority',
      async () => {
        const res = await pgrest.rest(makeEvent({
          path: '/rest/v1/people',
          query: {
            or: '(status.in.(vip,cancelled),'
              + 'priority.eq.medium)',
          },
        }));
        assert.deepStrictEqual(names(res),
          ['Bob', 'Charlie', 'Diana']);
      });
  });

  describe('is operator inside or', () => {
    it('assigned_to IS NULL OR priority=high', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/people',
        query: {
          or: '(assigned_to.is.null,priority.eq.high)',
        },
      }));
      assert.deepStrictEqual(names(res),
        ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve']);
    });
  });

  describe('is.true inside or', () => {
    it('featured IS TRUE OR status=vip', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/people',
        query: { or: '(featured.is.true,status.eq.vip)' },
      }));
      assert.deepStrictEqual(names(res),
        ['Alice', 'Bob', 'Charlie', 'Eve']);
    });
  });

  describe('negated condition inside or', () => {
    it('status.not.eq.active OR age.gt.65', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/people',
        query: {
          or: '(status.not.eq.active,age.gt.65)',
        },
      }));
      assert.deepStrictEqual(names(res),
        ['Bob', 'Charlie', 'Eve']);
    });
  });

  describe('like operator inside or', () => {
    it('name.like.A* OR name.like.B*', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/people',
        query: { or: '(name.like.A*,name.like.B*)' },
      }));
      assert.deepStrictEqual(names(res), ['Alice', 'Bob']);
    });
  });

  describe('not.in inside or', () => {
    it('status.not.in.(active,vip) OR age.gt.65',
      async () => {
        const res = await pgrest.rest(makeEvent({
          path: '/rest/v1/people',
          query: {
            or: '(status.not.in.(active,vip),age.gt.65)',
          },
        }));
        assert.deepStrictEqual(names(res),
          ['Charlie', 'Eve']);
      });
  });

  describe('single-condition logical group', () => {
    it('or with a single condition', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/people',
        query: { or: '(age.gt.65)' },
      }));
      assert.deepStrictEqual(names(res), ['Charlie']);
    });
  });

  // --- Combined with regular filters ---

  describe('combined with regular filters', () => {
    it('status=active AND (priority=high OR null assigned)',
      async () => {
        const res = await pgrest.rest(makeEvent({
          path: '/rest/v1/people',
          query: {
            status: 'eq.active',
            or: '(priority.eq.high,assigned_to.is.null)',
          },
        }));
        assert.deepStrictEqual(names(res),
          ['Alice', 'Diana']);
      });
  });

  describe('PostgREST canonical complex example', () => {
    it('priority=high AND featured AND or(age<18, '
      + 'not.and(18<=age<=30))', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/people',
        query: {
          priority: 'eq.high',
          featured: 'is.true',
          or: '(age.lt.18,'
            + 'not.and(age.gte.18,age.lte.30))',
        },
      }));
      assert.deepStrictEqual(names(res),
        ['Alice', 'Charlie']);
    });
  });

  describe('parameter numbering across groups', () => {
    it('regular filters on both sides of an or',
      async () => {
        const res = await pgrest.rest(makeEvent({
          path: '/rest/v1/people',
          query: {
            age: 'gt.10',
            or: '(status.eq.active,status.eq.vip)',
            name: 'neq.placeholder',
          },
        }));
        assert.deepStrictEqual(names(res),
          ['Alice', 'Bob', 'Diana', 'Frank']);
      });
  });

  // --- Logical operators with resource embedding ---

  describe('logical operators with resource embedding', () => {
    it('or with embedded select', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/orders',
        query: {
          select: 'id,amount,customers(name)',
          or: '(amount.gt.80,amount.lt.30)',
        },
      }));
      assert.equal(res.statusCode, 200);
      const rows = JSON.parse(res.body);
      const amounts = rows
        .map(r => Number(r.amount))
        .sort((a, b) => a - b);
      assert.deepStrictEqual(amounts, [25, 99]);
      // Verify embedding is present
      const order99 = rows.find(
        r => Number(r.amount) === 99);
      assert.ok(order99.customers,
        'order 99 should have embedded customer');
      assert.equal(order99.customers.name, 'Cust_Alice');
    });
  });

  describe('logical operators with count=exact', () => {
    it('or filter with limit and Prefer: count=exact',
      async () => {
        const res = await pgrest.rest(makeEvent({
          path: '/rest/v1/people',
          query: {
            or: '(age.lt.18,age.gt.65)',
            limit: '1',
          },
          headers: { Prefer: 'count=exact' },
        }));
        assert.equal(res.statusCode, 200);
        assert.match(res.headers['Content-Range'], /\/3$/);
      });
  });

  // --- Multi-value query parameters ---

  describe('multiple or params via multiValueQueryStringParameters',
    () => {
      it('two or values produce AND-joined groups',
        async () => {
          // API Gateway sets queryStringParameters to last
          // value and multiValueQueryStringParameters to all.
          const event = makeEvent({
            path: '/rest/v1/people',
            query: {
              or: '(priority.eq.high,priority.eq.medium)',
            },
            multiValueQuery: {
              or: [
                '(status.eq.vip,status.eq.active)',
                '(priority.eq.high,priority.eq.medium)',
              ],
            },
          });
          const res = await pgrest.rest(event);
          assert.deepStrictEqual(names(res),
            ['Alice', 'Diana']);
        });
    });

  describe('multiple or with single value (fallback)', () => {
    it('behaves identically to single or param',
      async () => {
        const event = makeEvent({
          path: '/rest/v1/people',
          query: { or: '(age.lt.18,age.gt.65)' },
          multiValueQuery: {
            or: ['(age.lt.18,age.gt.65)'],
          },
        });
        const res = await pgrest.rest(event);
        assert.deepStrictEqual(names(res),
          ['Alice', 'Charlie', 'Frank']);
      });
  });

  describe('multi-value not.or params', () => {
    it('two not.or values exclude both', async () => {
      const event = makeEvent({
        path: '/rest/v1/people',
        query: {
          'not.or': '(status.eq.refunded)',
        },
        multiValueQuery: {
          'not.or': [
            '(status.eq.cancelled)',
            '(status.eq.refunded)',
          ],
        },
      });
      const res = await pgrest.rest(event);
      assert.deepStrictEqual(names(res),
        ['Alice', 'Bob', 'Diana', 'Frank']);
    });
  });

  // --- Logical operators with mutations ---

  describe('logical operators with mutations', () => {
    it('PATCH with or filter', async () => {
      const res = await pgrest.rest(makeEvent({
        method: 'PATCH',
        path: '/rest/v1/people',
        query: {
          or: '(status.eq.cancelled,status.eq.refunded)',
        },
        body: { status: 'archived' },
        headers: { Prefer: 'return=representation' },
      }));
      assert.equal(res.statusCode, 200);
      const rows = JSON.parse(res.body);
      const updated = rows.map(r => r.name).sort();
      assert.deepStrictEqual(updated,
        ['Charlie', 'Eve']);
      for (const row of rows) {
        assert.equal(row.status, 'archived');
      }
    });

    it('DELETE with or filter', async () => {
      const del = await pgrest.rest(makeEvent({
        method: 'DELETE',
        path: '/rest/v1/people',
        query: {
          or: '(status.eq.cancelled,status.eq.refunded)',
        },
        headers: { Prefer: 'return=representation' },
      }));
      assert.equal(del.statusCode, 200);
      const deleted = JSON.parse(del.body)
        .map(r => r.name).sort();
      assert.deepStrictEqual(deleted,
        ['Charlie', 'Eve']);

      const after = await pgrest.rest(makeEvent({
        path: '/rest/v1/people',
      }));
      assert.deepStrictEqual(names(after),
        ['Alice', 'Bob', 'Diana', 'Frank']);
    });
  });

  // --- Error cases ---

  describe('error: empty or group', () => {
    it('returns 400 PGRST100', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/people',
        query: { or: '()' },
      }));
      assert.equal(res.statusCode, 400);
      const body = JSON.parse(res.body);
      assert.equal(body.code, 'PGRST100');
      assert.ok(
        body.message.includes(
          "Empty condition list in 'or' operator"),
        `expected empty-or error, got: ${body.message}`);
    });
  });

  describe('error: empty and group', () => {
    it('returns 400 PGRST100', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/people',
        query: { and: '()' },
      }));
      assert.equal(res.statusCode, 400);
      const body = JSON.parse(res.body);
      assert.equal(body.code, 'PGRST100');
      assert.ok(
        body.message.includes(
          "Empty condition list in 'and' operator"),
        `expected empty-and error, got: ${body.message}`);
    });
  });

  describe('error: nested empty and() inside or', () => {
    it('returns 400 PGRST100 with correct message',
      async () => {
        const res = await pgrest.rest(makeEvent({
          path: '/rest/v1/people',
          query: { or: '(and(),age.gt.18)' },
        }));
        assert.equal(res.statusCode, 400);
        const body = JSON.parse(res.body);
        assert.equal(body.code, 'PGRST100');
        assert.ok(
          body.message.includes(
            "Empty condition list in 'and' operator"),
          `expected nested empty-and error, `
          + `got: ${body.message}`);
      });
  });

  describe('error: nested empty or() inside and', () => {
    it('returns 400 PGRST100 with correct message',
      async () => {
        const res = await pgrest.rest(makeEvent({
          path: '/rest/v1/people',
          query: { and: '(or(),status.eq.active)' },
        }));
        assert.equal(res.statusCode, 400);
        const body = JSON.parse(res.body);
        assert.equal(body.code, 'PGRST100');
        assert.ok(
          body.message.includes(
            "Empty condition list in 'or' operator"),
          `expected nested empty-or error, `
          + `got: ${body.message}`);
      });
  });

  describe('error: unbalanced parentheses', () => {
    it('returns 400 PGRST100', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/people',
        query: { or: '(age.lt.18' },
      }));
      assert.equal(res.statusCode, 400);
      const body = JSON.parse(res.body);
      assert.equal(body.code, 'PGRST100');
      assert.ok(
        body.message.includes('Unbalanced parentheses'),
        `expected unbalanced-parens error, `
        + `got: ${body.message}`);
    });
  });

  describe('error: bad column in logical group', () => {
    it('returns 400 PGRST204 for bad_col', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/people',
        query: { or: '(bad_col.eq.1,age.gt.18)' },
      }));
      assert.equal(res.statusCode, 400);
      const body = JSON.parse(res.body);
      assert.equal(body.code, 'PGRST204');
      assert.ok(body.message.includes('bad_col'),
        `expected bad_col in error, got: ${body.message}`);
    });
  });

  describe('error: bad operator in logical group', () => {
    it('returns 400 PGRST100 for bad_op', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/people',
        query: { or: '(age.bad_op.18,name.eq.x)' },
      }));
      assert.equal(res.statusCode, 400);
      const body = JSON.parse(res.body);
      assert.equal(body.code, 'PGRST100');
      assert.ok(body.message.includes('bad_op'),
        `expected bad_op in error, got: ${body.message}`);
    });
  });

  describe('error: trailing paren only', () => {
    it('returns 400 PGRST100', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/people',
        query: { or: 'age.lt.18)' },
      }));
      assert.equal(res.statusCode, 400);
      const body = JSON.parse(res.body);
      assert.equal(body.code, 'PGRST100');
      assert.ok(
        body.message.includes('Unbalanced parentheses'),
        `expected unbalanced-parens error, `
        + `got: ${body.message}`);
    });
  });

  describe('error: bad filter syntax in logical group', () => {
    it('returns 400 PGRST100 for condition with no dot',
      async () => {
        const res = await pgrest.rest(makeEvent({
          path: '/rest/v1/people',
          query: { or: '(novalue)' },
        }));
        assert.equal(res.statusCode, 400);
        const body = JSON.parse(res.body);
        assert.equal(body.code, 'PGRST100');
        assert.ok(
          body.message.includes(
            'not a valid filter condition'),
          `expected filter condition error, `
          + `got: ${body.message}`);
      });
  });

  // --- Recursion depth limit ---

  describe('excessive nesting depth rejected', () => {
    it('test_excessive_nesting_depth_rejected', async () => {
      // Build 15 levels: or=(and(or(and(...a.eq.1...))))
      let inner = 'age.eq.15';
      for (let i = 0; i < 14; i++) {
        const op = i % 2 === 0 ? 'and' : 'or';
        inner = `${op}(${inner})`;
      }
      // inner is now 14 levels of nesting around age.eq.15
      // The top-level or= adds the 15th level
      const query = { or: `(${inner})` };

      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/people',
        query,
      }));
      assert.equal(res.statusCode, 400);
      const body = JSON.parse(res.body);
      assert.equal(body.code, 'PGRST100');
      assert.ok(
        body.message.includes(
          'Logical operator nesting exceeds maximum '
          + 'depth of 10'),
        `expected nesting depth error, `
        + `got: ${body.message}`);
    });
  });

  describe('nesting at exactly depth 10 succeeds', () => {
    it('test_nesting_at_max_depth_succeeds', async () => {
      // Build 9 levels of nesting inside top-level or=
      // (which counts as depth 0), totaling depth 10.
      let inner = 'name.eq.Alice';
      for (let i = 0; i < 9; i++) {
        const op = i % 2 === 0 ? 'and' : 'or';
        inner = `${op}(${inner})`;
      }
      const query = { or: `(${inner})` };

      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/people',
        query,
      }));
      assert.equal(res.statusCode, 200,
        `expected 200 for depth-10 nesting, `
        + `got ${res.statusCode}: ${res.body}`);
      const rows = JSON.parse(res.body);
      assert.ok(rows.length >= 1,
        'expected at least one row for name.eq.Alice');
    });
  });

  // --- Backward compatibility ---

  describe('backward compatibility: regular filters', () => {
    it('age>18 AND status=active unchanged', async () => {
      const res = await pgrest.rest(makeEvent({
        path: '/rest/v1/people',
        query: { age: 'gt.18', status: 'eq.active' },
      }));
      assert.deepStrictEqual(names(res), ['Diana']);
    });
  });

  describe('value without outer parentheses', () => {
    it('or=age.lt.18,age.gt.65 handled gracefully',
      async () => {
        const res = await pgrest.rest(makeEvent({
          path: '/rest/v1/people',
          query: { or: 'age.lt.18,age.gt.65' },
        }));
        assert.deepStrictEqual(names(res),
          ['Alice', 'Charlie', 'Frank']);
      });
  });

  describe('backward compat: not. prefix on regular filters',
    () => {
      it('status=not.eq.active returns non-active people',
        async () => {
          const res = await pgrest.rest(makeEvent({
            path: '/rest/v1/people',
            query: { status: 'not.eq.active' },
          }));
          assert.deepStrictEqual(names(res),
            ['Bob', 'Charlie', 'Eve']);
        });
    });
});
