export const AUTH_SCHEMA_SQL = [
  'CREATE SCHEMA IF NOT EXISTS auth',

  `CREATE TABLE IF NOT EXISTS auth.users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT NOT NULL,
    encrypted_password TEXT NOT NULL,
    email_confirmed_at TIMESTAMPTZ DEFAULT now(),
    role TEXT NOT NULL DEFAULT 'authenticated',
    aud TEXT NOT NULL DEFAULT 'authenticated',
    app_metadata JSONB NOT NULL DEFAULT '{"provider":"email","providers":["email"]}'::jsonb,
    user_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
  )`,

  'CREATE UNIQUE INDEX IF NOT EXISTS auth_users_email_idx ON auth.users (email)',

  `CREATE TABLE IF NOT EXISTS auth.refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1) PRIMARY KEY,
    token TEXT NOT NULL,
    user_id UUID NOT NULL,
    parent TEXT,
    revoked BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
  )`,

  'CREATE UNIQUE INDEX IF NOT EXISTS auth_refresh_tokens_token_idx ON auth.refresh_tokens (token)',

  'CREATE INDEX IF NOT EXISTS auth_refresh_tokens_user_id_idx ON auth.refresh_tokens (user_id)',

  `CREATE TABLE IF NOT EXISTS auth.sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    provider TEXT NOT NULL,
    prt TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    revoked BOOLEAN NOT NULL DEFAULT false
  )`,

  'CREATE INDEX IF NOT EXISTS auth_sessions_user_id_idx ON auth.sessions (user_id)',
];

let initialized = false;

export async function ensureAuthSchema(pool) {
  if (initialized) return;
  for (const sql of AUTH_SCHEMA_SQL) {
    await pool.query(sql);
  }
  initialized = true;
}

export function _resetInitialized() {
  initialized = false;
}
